nagybalazs/homework-3
Global-rd/python_hu pull request #102
Opened 2024-10-12 12:43 UTC by balanagy23

A kő-papír-ollós feladattal megharcoltam :) Bocsánat megint tettem bele plusz funkciókat remélem most sem lesz zavaró. Előre is köszönöm a visszajelzéseket!

2024-10-14 19:27 UTC, NagyIstvanGabor requested changes
Szia!

Szuper a házi, köszi szépen! Van néhány apróság amit javítani kéne, mindegyikhez írtam külön egy-egy kommentet. Ha ezek megvannak, megy is az approve.

Köszi szépen!

2024-10-15 05:15 UTC, balanagy23 commented on homeworks/nagybalazs/3_conditionals_loop/flat_finder.py
> +name_of_city = input("In which city is the apartment located? ").capitalize()
Bocsánat ezt abbahagyom csak a print- fontos a normális formátum nekem :D OCD sorry

2024-10-15 05:53 UTC, balanagy23 commented
Köszönöm a tippeket és az észrevételeket! Bocsánat a sok sallangért még nagyon kezdő vagyok igyekszem ezeket csak módjával használni.

2024-10-15 20:56 UTC, NagyIstvanGabor requested changes
Szia!

Semmi gond nincs, szuperül reagáltál az összes változtatási kérésre!
Egyetlen egy dolog maradt ki, a rock_paper_scissors.py 28. során még bent maradt változatlanul ez a sor:
`if answer_player_1 and answer_player_2  in ["rock", "paper", "scissors"]:`

Kommentben írtam alatta hogy hogy kéne átírni. Köszi!

2024-10-16 05:18 UTC, balanagy23 commented
Bocsánat valahogy a rock_paper_scissors.py feltöltését kivettem a feltöltésből. Frissítettem. Köszönöm!

2024-10-16 07:31 UTC, NagyIstvanGabor approved these changes
Szia!

Így már szuper, köszönöm szépen! Approve-oltam, mehet is a merge.

2024-10-16 08:05 UTC, merged