homework_3
Global-rd/python_hu pull request #103
Opened 2024-10-12 16:42 UTC by barnaf03

Szia! A Discordon írtam, hogy elég nagy technikai gondban vagyok, így kénytelen voltam megvenni az androidos verziót, hogy tudjak haladni. Elég nagy kihívás volt ez a kő-papír-olló, többet nem kérek belőle. De legalább megtanultam használni a while ciklust, és értem is  használatát!

2024-10-14 19:36 UTC, NagyIstvanGabor requested changes
Szia!

Öröm volt ránézni erre a házira, gratulálok!
Egy apróságot kérek csak pluszban, hogy a 2. feladatban a Tie-hoz tedd be a continue-t. Ott elmagyaráztam részletesebben, de ezzel gyakorlatilag kizárod a döntetlent.

Köszi szépen!

2024-10-14 19:36 UTC, NagyIstvanGabor commented on homeworks/feherbarnabas/3_conditionals_loops/rock_paper_scissors.py
> +            print("It's a tie!")
```
if player_1 == player_2:
       print("It's a tie!")
       continue
```

Ha berakod ide a continue-t, akkor anélkül fogja újrakezdeni a loop-ot, hogy növelnéd a current_round értékét. 
Ezzel kizárod, hogy döntetlen legyen, mert minden kör addig megy, ameddig eltérő értéket nem adnak meg.

2024-10-14 19:38 UTC, barnaf03 commented on homeworks/feherbarnabas/3_conditionals_loops/rock_paper_scissors.py
> +            print("It's a tie!")
Rendben! Köszönöm!

2024-10-15 20:57 UTC, NagyIstvanGabor approved these changes
Szuper, köszönöm szépen!
Approve-oltam is, mehet a merge!

2024-10-21 08:19 UTC, merged