pontazsolt_homework3
Global-rd/python_hu pull request #109
Opened 2024-10-12 22:51 UTC by PontaZsolt

2024-10-15 09:05 UTC, NagyIstvanGabor requested changes
Szia!

Nagyon szép házi! A rock-paper-scissors-ban van egy apró változtatási lehetőség ami életközelibbé tenné a játékot, ehhez odaírtam kommentben a részleteket.
Ezt javítsd kérlek, és ha ez megvan megy is az approve.

Köszi szépen!

2024-10-15 09:05 UTC, NagyIstvanGabor commented on homeworks/pontazsolt/3_conditionals_loops/rock_paper_scissors.py
> +        print("The result is a draw")
Szuper lenne ha nem tudnának döntetlent játszani egy körben, és ehhez elég lenne egy apró változtatás:

```
current_round = 1
#Körök iterálása
#for round in range(count_rounds):
while current_round <= count_rounds:
    print(f"\n{current_round}. kör: ")

    #Első játékos köre:
    while True:
        player1_choice = input("Player 1 turn: 'rock', 'paper' or 'scissors'?: " ).lower()
        if player1_choice in ["rock", "paper", "scissors"]:
            break
        else:
            print(f"Choose one of them: 'rock', 'paper', 'scissors': ")

    #Második játékos köre:
    while True:
        player2_choice = input("Player 2 turn: 'rock', 'paper' or 'scissors'?: " ).lower()
        if player2_choice in ["rock", "paper", "scissors"]:
            break
        else:
            print("Choose one of them: 'rock', 'paper', 'scissors': ")

    #Eredmény meghatározása:
    if player1_choice == player2_choice:
        print("The result is a draw, try again!")
        continue
    elif (player1_choice == 'rock' and player2_choice == 'scissors') or \
         (player1_choice == 'scissors' and player2_choice == 'paper') or \
         (player1_choice == 'paper' and player2_choice == 'rock'):
        print("Player 1 won that round")
        player1_score += 1
    else:
        print("Player 2 won that round")
        player2_score += 1
    
    current_round += 1
```

Ami it történik:
bevezettünk egy current_round változót, és a for ciklust lecseréltük egy while ciklusra. Ha döntetlen az aktuális kör, a continue-val addig fogja újrakezdeni az aktuális kört, amíg eltérő értéket nem adnak meg (van a conditional végén egy current_round += 1, ez nem fut le, ha a continue meghívódik. Így csak akkor megyünk a következő körre ha nem döntetlen az aktuális kör eredménye.

2024-10-15 09:05 UTC, NagyIstvanGabor commented on homeworks/pontazsolt/3_conditionals_loops/rock_paper_scissors.py
> +else:
Ha a fenti tanácsot megfogadod, ez sem kell, mert nem lehet döntetlen a végeredmény.

2024-10-18 18:44 UTC, PontaZsolt commented
Átnéztem, értelmeztem és javítottam a dolgokat. Köszi a tanácsot!

2024-10-19 17:35 UTC, NagyIstvanGabor approved these changes
Szia!

Szuper, nagyon szépen köszönöm a változtatásokat! Approve-oltam is, mehet a merge.

2024-10-21 19:13 UTC, merged