3. házifeladat
Global-rd/python_hu pull request #113
Opened 2024-10-13 11:44 UTC by Methmat

elkészítettem a 3. házit

2024-10-15 09:48 UTC, NagyIstvanGabor requested changes
Szia!
Az első feladathoz írtam néhány apróságot.
A második feladatodban lehetséges a döntetlen, mégis a következő eredményt írja ki a kódod:

```
A játék véget ért!
1. Játékos pontjai: 0
2. Játékos pontjai: 3
2. Játékos nyert a játékot!
```

(Mindhárom körben paper-t adtam meg mind a két oldalról). Javítsd kérlek úgy, hog eleve ne tudjanak döntetlent játszani (minden kör addig ismétlődjön amíg eltérő input-ot nem adnak meg).

2024-10-15 09:48 UTC, NagyIstvanGabor commented on homeworks/nemethmate/3_conditionals_loops/flat_finder.py
> +if city.lower() == "new york" or city.lower() == "san francisco":
a lower()-t meghívhatnád az első soron is, és így itt nem lenne szükség arra hogy kétszer külön is meghívd.
valamint használhatnál membership operator-okat hogy egyszerűbb legyen:

`if city in ["new york", "san francisco"]:`

2024-10-15 09:48 UTC, NagyIstvanGabor commented on homeworks/nemethmate/3_conditionals_loops/flat_finder.py
> +else:
ez az else és a belőle induló if-else egybeolvasztható:

```
    elif rent <= 3000:
        result = "Be tudok költözni"
    else:
        result = "Nem tudok beköltözni"
```

2024-10-16 14:46 UTC, Methmat commented on homeworks/nemethmate/3_conditionals_loops/flat_finder.py
> +else:
basszus valóban. Köszi.

2024-10-16 21:10 UTC, NagyIstvanGabor submitted a review, later dismissed
Köszi szépen a változtatásokat, approve-oltam is. Mehet a merge.

2024-10-28 19:58 UTC, NagyIstvanGabor requested changes
Szia!

Tök jó a 4-es házid, azzal kapcsolatban csak két dolog:
-maradhat a tasks.json a PR-ban, de a kódot is módosítsd (írtam kommentet) hogy a te mappádba írja a file-t, és a már meglévő file-t töröld a root-ból kérlek.

PR:
Nem merge-ölted be a jóváhagyott 3-as házidat, és most ugyanarról a branch-ról nyitottad a 4-est is.
Így updatelted a 3. házifeladat PR-ját a 4-es házival is. 
Azt csak most vettem észre hogy mindezt egy "nemethmate_homework_2" nevű branch-ről tetted :). 
Ettől a résztől most tekintsünk el, mert nem akarom túlbonyolítani a feladatot, de erről a branch-ről töröld kérlek a 4-es házi mappáját, hogy csak a 3_conditionals_loops maradjon.
Aztán push-old a változtatást és akkor jóváhagyom erről a branch-ról a 3-as házit újra és a 4-est küldd be egy külön branch-ról (csinálj egy nemethmate_homework_4 branch-et) nyitott PR-ban.

Lépések:
1. csinálj egy nemethmate_homework4 branch-et a nemethmate_homework_2 alapján.
2. ezen a 4-es branchen töröld a 3_conditionals_loops mappát, és nyiss egy PR-t (plusz a változtatások a json path-tel amit írtam)
3. Menj át a homework-2 mappára ahol a 3-as házi van, és innen töröld a 4_exceptions_logging mappát, és a tasks.json-t a root-ból. Így visszaállítod a 3-as házit a már jóváhagyott állapotára. Nyisd újra a pr-t itt is, és jóváhagyom újra.

Köszi szépen.

2024-11-05 07:23 UTC, NagyIstvanGabor requested changes
Szia!

Majdnem tökéletes, a 4-es házid eltűnt, viszont a tasks.json-t bent felejtetted a root-ban.
![image](https://github.com/user-attachments/assets/5ce85f16-2781-428d-909a-74fa37a23a2f)
![image](https://github.com/user-attachments/assets/0321ce9d-f84a-4137-972d-f42ae757f197)

Ezt töröld ki kérlek, és approve-olom.  Köszi szépen!

2024-11-06 08:05 UTC, Methmat commented
> Szia!
> 
> Majdnem tökéletes, a 4-es házid eltűnt, viszont a tasks.json-t bent felejtetted a root-ban. ![image](https://private-user-images.githubusercontent.com/63602487/383044652-5ce85f16-2781-428d-909a-74fa37a23a2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4ODA2MDksIm5iZiI6MTczMDg4MDMwOSwicGF0aCI6Ii82MzYwMjQ4Ny8zODMwNDQ2NTItNWNlODVmMTYtMjc4MS00MjhkLTkwOWEtNzRmYTM3YTIzYTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA4MDUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ZDhhNjU2M2VjYTQ2ZDc5NGMzZmFhOGIwZmYwMzI4OTFhZjY4YThhMjUzMDZlZmJmNDE2M2M3Y2MwYTM4MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.b42jzb7oINPQFs3qV83NBn0xuB0ksJVBaihCYlrDxFk) ![image](https://private-user-images.githubusercontent.com/63602487/383044940-0321ce9d-f84a-4137-972d-f42ae757f197.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4ODA2MDksIm5iZiI6MTczMDg4MDMwOSwicGF0aCI6Ii82MzYwMjQ4Ny8zODMwNDQ5NDAtMDMyMWNlOWQtZjg0YS00MTM3LTk3MmQtZjQyYWU3NTdmMTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA4MDUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmMjk5MjkwYjgxYjdjOWExOTMzZTAwMjViYTgxZTRkNGZkM2EyNjBkNTNhNjM1Y2UyNGRjYzg1OTBiY2M1MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FiI8Jj8c_Migd4T6mFP26vGDoi0z6Oe1u09dCOamL50)
> 
> Ezt töröld ki kérlek, és approve-olom. Köszi szépen!

_okés Töröltem. Köszi

2024-11-06 19:17 UTC, NagyIstvanGabor approved these changes
Szuper köszi szépen! Approve-oltam, mehet a merge.

2024-11-07 17:29 UTC, merged