zsoltcsengeri/homework 3
Global-rd/python_hu pull request #114
Opened 2024-10-13 13:06 UTC by zsoltcsengeri

Szia István!

Feltöltöttem a kódok végleges verzióját, és be kell vallanom, hogy nem csak az órán használt forrásokat vettem igénybe, hanem a ChatGPT-t is segítségül hívtam, hogy jobban megértsem a logikát, különösen a jegyfoglalási feladatnál, ami elég challenging volt. Nem érzem még magam magabiztosnak az összes nyelvi szintaxis és megoldás használatában, amit az órákon mutattál, de természetesen sokat tanultam, és remélem, hogy később jobban fog menni!

Nagyon köszönöm az eddigi órákat!

Üdv, Zsolt

2024-10-15 15:15 UTC, NagyIstvanGabor requested changes
Szia!

Először is köszi szépen az őszinteséged :). Semmi gond nincs azzal, ha chatGPT-t használsz, amíg kezdőként jó célra használod. Ahogy írtad is, amíg az a célod vele hogy jobban megértsd valaminek a működését, elmagyaráztatsz vele dolgokat, vagy csak a programod bizonyos részeit iratod meg vele amit **aztán alaposan átnézel és értelmezel**, a chatGPT egy nagyon hasznos eszköz.
Az órákon is téma lesz az LLM-ek használata, akkor egy kicsit részletesebben bele fogok menni hogy szerintem hogy lenne érdemes használnotok, de amíg nem arra használod hogy ctrl+c ctrl+v bemásold a generált kódot, addig csak tanulni tudsz belőle.
Az eddigi házijaidon is látszik, hogy beleteszed a kellő munkát, szóval ne aggódj ha még nem érzed magabiztosnak magad, elegendő gyakorlással simán menni fog.

Rátérve a házidra: Az első és második feladatban találtam néhány apró javítani valókat, ezekhez odaírtam részletesen is a teendőket. Ha ezek megvannak, megy is az approve. Köszi szépen!

2024-10-15 15:15 UTC, NagyIstvanGabor commented on homeworks/zsoltcsengeri/3_conditional_loops/flat_finder.py
> +    rental_city = input(
Értem a logikát, hogy ha Washington-t adja meg a felhasználó, akkor automatikusan bekérsz egy új várost, de ha makacs, és újra megadja Washington-t, akkor ez lesz az eredmény:

```
Sarah: Which city can you offer for renting an apartment in? Washington
Sarah: Sorry, but I really don't like Washington. No way!
Sarah: Which city can you offer for renting an apartment in? Washington
Sarah: Ok, and how much is the rent for the apartment in dollars? 2500
Sarah: The rent in Washington is reasonable, so I'm interested!
```

Ha szeretnéd ezt a logikát tartani, akkor egy while loop-pal tudod biztosítani, hogy addig nem megy tovább a programod amíg a felhasználó Washington-t adja meg inputként. 

Valahogy így:

```
# Tuple for New York and San Francisco
cities_to_consider = ("New York", "San Francisco")


while True:
# Get the city
    rental_city = input(
        f"{SARAH}: Which city can you offer for renting an apartment in? ").strip().title()

# Immediate response for Washington and Chicago
    if rental_city == "Washington":

        print(f"{SARAH}: Sorry, but I really don't like {rental_city}. No way! Please offer something else!")
        continue
```

A conditional-ök végén pedig break-elsz, hogy kilépj a loop-ból:

```
        else:
            if apartment_rent_price <= 3000:
                print(f"{SARAH}: The rent in {
                    rental_city} is reasonable, so I'm interested!")
            else:
                print(f"{SARAH}: The rent in {
                    rental_city} is too high for me, so I'll pass.")
    break
```

2024-10-15 15:15 UTC, NagyIstvanGabor commented on homeworks/zsoltcsengeri/3_conditional_loops/rock_paper_scissors.py
> +        print("It's a draw!")
ha ide betennél egy `continue`-t, kizárhatnád a döntetlen esélyét mind az adott körben, mint a végeredményben.
A continue miatt ha ugyanazt adják meg, újrakezdődik ugyanaz az iteráció (alapesetben ugye a continue-val továbbmegyünk, de mivel ez egy while True, a continue miatt nem jut el a current_set += 1-ig. Így addig játszák újra a kört ameddig különböző inputot nem adnak meg.
Így a 86. soron lévő elif sem kell, mert fixen nyerni fog valaki.

2024-10-16 20:06 UTC, zsoltcsengeri commented
Szia István!

Köszönöm szépen a visszajelzéseket és a bíztató szavakat!Elvégeztem a javasolt módosításokat a kódjaimban, és nagyon örülök, hogy segítettek jobban átlátni néhány dolgot. Az órák mellett a ChatGPT-t tényleg arra használom, hogy jobban megértsem a logikát és a megoldásokat, de természetesen igyekszem minden kódot alaposan átnézni és megérteni.

Tényleg rengeteget tanultam az eddigi feladatokból, és nagyon várom a további kihívásokat is! Köszönöm a folyamatos segítséget és útmutatást, remélem, hogy a jövőben egyre magabiztosabb leszek.

Várom az újabb órákat és a következő feladatokat! :)

Üdvözlettel,
Zsolt

2024-10-16 21:22 UTC, NagyIstvanGabor requested changes
Szia Zsolt!

Köszi szépen a változtatásokat! Valami gond van viszont most a PR-oddal, mivel most 72 file változtatását merge-ölnénk ba ha jóváhagynám. Köztük vannak más tanulók mappái is.
Megpróbálnád kérlek a következőket?
1. Mentsd ki a saját 3_conditionals_loops mappádat valahova a local repo-n kívülre
2. töröld ezt a branch-et (amikor a github desktop feldobja a kérdést, akkor pipáld be hogy törölje remote-ról is)
3. válts át a main branch-re, fetch, pull
4. hozd létre az új homework-3 branch-et, és másold ide vissza a 3_conditionals_loops mappádat a saját neved alatt lévő mappába.
Ezután nyiss kérlek egy új PR-t, és azt jóváhagyom. Köszi szépen!
![image](https://github.com/user-attachments/assets/0d8d9bde-24b6-42aa-b9c8-5a855b099f62)

2024-10-16 22:28 UTC, closed without merging