Asztaloslajos/homework3
Global-rd/python_hu pull request #115
Opened 2024-10-13 14:08 UTC by AsztalosLajos

2024-10-15 15:41 UTC, NagyIstvanGabor requested changes
Szia!

Írtam pár kommentet, egyszerűsítési lehetőségekkel. Amit a második feladat 24.-es sorához írtam, javítsd kérlek, mert jóval python-osabb és egyszerűbb a megoldás amit kommentben írtam. A második teljesen rendben van, elég ha átolvasod azt a kommentet, hogy a jövőben hasznosítsd a tudást.
Összességében szép munka, ha ez az egy változtatás megvan, megy is az approve. Köszi szépen!

2024-10-15 15:41 UTC, NagyIstvanGabor commented on homeworks/asztaloslajos/3_conditionals_loop/flat_finder.py
> +elif ((city == "New York" or city == "San Fransisco") and apartment_rent < 4000) or apartment_rent <=3000 or city == "Chicago":
Nem hiba, csak egy rövidítési lehetőség:

`city in ['San Francisco', 'New York']`, ezzel kicsit egyszerűsíteni tudod az elif-et

2024-10-15 15:41 UTC, NagyIstvanGabor commented on homeworks/asztaloslajos/3_conditionals_loop/rock_paper_scissors.py
> +    i=False
ezt a két while loopot ahol a játékosok tippjeit kéred be, lehet egy kicsit egyszerűsíteni:

```
    while True:
        a_player_bet = input(f"Az első játékos {round}. tétje:")
        if a_player_bet in RPS:
            break
        print("A megadott érték csak kő, papír vagy olló lehet!")
    #input second bet
    while True:
        b_player_bet = input(f"A második játékos {round}. tétje:")
        if b_player_bet in RPS:
            break
        print("A megadott érték csak kő, papír vagy olló lehet!")
```

Ami itt történik az az, hogy ha a megadott válasz benne van az RPS-ben akkor kilépünk a ciklusból, ha nem, akkor kiprinteljük hogy rosszat adott meg, és újra próbálkozunk a while True miatt. Persze ezt is tovább lehetne egyszerűsíteni ha function-öket használnánk, de ez a házi még nem tartozott a function-ös témakörbe.

2024-10-15 15:41 UTC, NagyIstvanGabor commented on homeworks/asztaloslajos/3_conditionals_loop/rock_paper_scissors.py
> +    #evaluation
Ez nem hiba, mert ha szeretnél ennyire részletes infot adni arról hogy mi történt, akkor érthető a megoldásod, csak szerettem volna megmutatni hogy ha egyszerűsíteni akarnál, akkor hogyan lehetne:
```
round = 1
while round <= rounds_num:
    
    print(f"Forduló:{round}, A:{a_score}, B:{b_score}")
    #input first bet
    
    while True:
        a_player_bet = input(f"Az első játékos {round}. tétje:")
        if a_player_bet in RPS:
            break
        print("A megadott érték csak kő, papír vagy olló lehet!")
    #input second bet
    while True:
        b_player_bet = input(f"A második játékos {round}. tétje:")
        if b_player_bet in RPS:
            break
        print("A megadott érték csak kő, papír vagy olló lehet!")


    #evaluation
    if a_player_bet == b_player_bet:
        continue
    elif ((a_player_bet == "kő" and b_player_bet == "olló")
         or (a_player_bet == "olló" and b_player_bet == "papír")
         or (a_player_bet=="papír" and b_player_bet=="kő")):
        a_score += 1
    else:
        b_score += 1
    
    round += 1
```

2024-10-15 21:03 UTC, NagyIstvanGabor approved these changes
Köszi szépen a változtatásokat! Approve-oltam, mehet a merge!

2024-10-16 16:39 UTC, merged

2024-10-16 16:39 UTC, AsztalosLajos commented
Köszönöm a sok segítséget és az ötleteket!