Jonasnikolett/homework 3
Global-rd/python_hu pull request #116
Opened 2024-10-13 15:52 UTC by jonasnikolett90

1. és 2. feladat
az extra házit sajnos a héten nem tudom időben megrni

2024-10-15 15:49 UTC, NagyIstvanGabor requested changes
Szia!

Az első feladatodban van egy pici hiba, leírtam a részleteket kommentben. A második feladatod szuper, nagyon pozitív hogy lekezelted a körönkénti döntetleneket!
Ha ezt a pici változtatást megcsinálod, megy is az approve. Szép munka, köszi szépen!

2024-10-16 19:09 UTC, jonasnikolett90 commented
Megpróbáltam lekövetni az egészet amit írtál kommentben. Remélem sikerült jól megírnom, bár a gépemen nem volt időm most minden kimenetet végig próbálnom.
Ha nem jó hétvégén fogok tudni vele tovább dolgozni. :-)

2024-10-16 21:30 UTC, NagyIstvanGabor requested changes
Szia!

A Chicago-s ágnál nincs szükség a continue-ra, akkor nem akarjuk újra bekérni az input-ot, oda szívesen költözik :) Illetve ez lehet egy elif, mivel nem különálló vizsgálandó logika. Nézd meg kérlek a kódot amit kommentben írtam, az egy lehetséges jó megoldás.

A kódod jelenleg indentation hibák miatt nem fut le, ha nem nyúlok bele, ezeket kérlek javítsd. Neonzölddel megjelöltem ahol van egy fölös space:

![image](https://github.com/user-attachments/assets/c2c1168c-e1b4-4899-bfba-4911faa199e2)

Itt pedig szintén neonzölddel, hogy a második if-ben a jobban behúztad egy tab-bal a  végrehajtandó logikát.
Köszi szépen!

2024-10-26 12:36 UTC, jonasnikolett90 commented
Szia!
Köszi a segítséget az elif-fel sikeresen lefut. A behuzásos hibákat is javítottam.

2024-10-26 18:16 UTC, NagyIstvanGabor approved these changes
Szia!

Köszi szépen a változtatásokat! Approve-oltam is, mehet a merge.

2024-10-26 19:31 UTC, merged