zlinszkygyorgy/homework3
Global-rd/python_hu pull request #118
Opened 2024-10-13 17:50 UTC by gzlinsz

2024-10-15 15:58 UTC, NagyIstvanGabor requested changes
Szia!

Szuper a házid, két apró változtatást kértem csak be az első feladathoz, ha ezek megvannak megy is az approve.

Köszi szépen!

2024-10-15 15:58 UTC, NagyIstvanGabor commented on homeworks/zlinszkygyorgy/3_conditionals_loops/flat_finder.py
> +elif city == "New York" or city == "San Francisco":
Nem hiba, csak egy egyszerűsítési lehetőség:

`elif city in ["New York", "San Francisco"]:`

a membership operátorral rövidíteni tudod a kódot, mert nem kell többször is szembeállítani a változót a vizsgálandó értékkel.

2024-10-15 15:58 UTC, NagyIstvanGabor commented on homeworks/zlinszkygyorgy/3_conditionals_loops/flat_finder.py
> +else:
ezt olvaszd egybe kérlek, nem kell egy else és abba egy új if-else:
```

    elif rental_fee <= 3000:
        print(f"You can rent a flat in {city} for {rental_fee} USD")
    else:
        print(f"You cannot rent a flat in {city} for {rental_fee} USD")
```

2024-10-16 16:28 UTC, gzlinsz commented
Szia módosítottam. Commit-oltam, push-oltam, látom is itt, de nem értem, miért nem kért pull requestet.

2024-10-16 21:32 UTC, NagyIstvanGabor approved these changes
Szia, köszi szépen a változtatásokat, approve-oltam, mehet a merge!
Azért nem kért új pull request-et, mert még nyitva van az eredeti. Ilyenkor amit push-olsz, az megváltoztatja az eredeti pull request-ed tartalmát. Nem kell mindig újat nyitni.
Ezáltal visszakövethető az is, hogy én milyen változtatást kértem, és te arra hogy reagáltál, mindezt egy pull request-en belül.

2024-10-17 09:06 UTC, merged