Schreinerbalazs/homework 3
Global-rd/python_hu pull request #122
Opened 2024-10-14 07:04 UTC by snerbalu

2024-10-15 09:35 UTC, NagyIstvanGabor reviewed
Szia!

Van már egy másik PR-od amiben csak a harmadik házit módosítod. Ebben más tanulók mappáját is módosítod, ezt a PR-t kérlek zárd.

2024-10-15 16:34 UTC, NagyIstvanGabor requested changes
Már van egy jó PR-od, ebben más tanulók mappájában történnek változtatások.
Szerintem ezt nyugodtan töröld, de ha esetleg tudok segíteni valamit a git-tel, jelezd discordon kérlek.
![image](https://github.com/user-attachments/assets/38484ca6-b6c9-45c3-a48c-c3113008f50e)

2024-10-28 20:02 UTC, NagyIstvanGabor requested changes
Szia!

Ez így sajnos ebben a formában még nem jó, mert törölsz pár mappát amit nem kéne:

![image](https://github.com/user-attachments/assets/48987435-14de-4ac8-a6e4-c16bba2e152f)

A legegyszerűbb megoldás amit tehetsz, hogy kimásolod valahova a repo-n kívülre a teljes 3_conditionals_loops mappádat, majd törlöd ezt a branch-et a github desktop-ban úgy ahogy van (nyugodtan pipáld be hogy remote-on is törölje). Ezzel ezt a PR-t zárni fogja automatikusan. 
Ezután válts át a main branch-re github desktopban, fetch, pull. Majd csinálj egy új branch-et a main alapján schreinerbalazs-homework03 néven (vagy valami hasonló).
Másold vissza az asztalról ide a mappádat, és nyithatod az új PR-t, amiben így már nem lesznek törlések.

Köszi szépen!

2024-10-30 14:20 UTC, closed without merging

2024-10-30 14:25 UTC, snerbalu commented
Szia,

remélem most jó.
Github-ban teljesen el vagyok veszve. 🤡

Köszönöm!

NagyIstvanGabor ***@***.***> ezt írta (időpont: 2024. okt.
28., H, 21:02):

> ***@***.**** requested changes on this pull request.
>
> Szia!
>
> Ez így sajnos ebben a formában még nem jó, mert törölsz pár mappát amit
> nem kéne:
>
> image.png (view on web)
> <https://github.com/user-attachments/assets/48987435-14de-4ac8-a6e4-c16bba2e152f>
>
> A legegyszerűbb megoldás amit tehetsz, hogy kimásolod valahova a repo-n
> kívülre a teljes 3_conditionals_loops mappádat, majd törlöd ezt a branch-et
> a github desktop-ban úgy ahogy van (nyugodtan pipáld be hogy remote-on is
> törölje). Ezzel ezt a PR-t zárni fogja automatikusan.
> Ezután válts át a main branch-re github desktopban, fetch, pull. Majd
> csinálj egy új branch-et a main alapján schreinerbalazs-homework03 néven
> (vagy valami hasonló).
> Másold vissza az asztalról ide a mappádat, és nyithatod az új PR-t, amiben
> így már nem lesznek törlések.
>
> Köszi szépen!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Global-rd/python_hu/pull/122#pullrequestreview-2400091955>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALCYZXA4EMPYYAEB4NRBI3LZ52C6DAVCNFSM6AAAAABP4KG2ICVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMBQGA4TCOJVGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>