Homework_03_done
Global-rd/python_hu pull request #124
Opened 2024-10-14 08:43 UTC by JanosV2

Done. It was comolicated :P :)

2024-10-15 16:58 UTC, NagyIstvanGabor requested changes
Szia!

Szuper a házid, viszont van egy két apróság amin jó lenne javítani. Ez leginkább a második feladatra igaz ahol egy szélsőséges eset nincs lekezelve. Odaírtam a részleteket kommentben. Köszi szépen!

2024-10-15 16:58 UTC, NagyIstvanGabor commented on homeworks/vulmanjanos/3_conditionals_loops/flat_finder.py
> +elif (city_name != "New York" or city_name != "San Fransisco" or city_name != "Washington" or city_name != "Chicago") and flat_price <= 3000:
Teljesen jó a megoldásod, de ez a feltétel szükségtelen, feljebb már ellenőrzöd ezeket a városokat, és mivel elif-et használsz, ha valamelyik fentebbi condition már lefutott, ez nem fog tudni.

2024-10-15 16:58 UTC, NagyIstvanGabor commented on homeworks/vulmanjanos/3_conditionals_loops/flat_finder.py
> +else:
ez viszont kell, és jó is így.

2024-10-15 16:58 UTC, NagyIstvanGabor commented on homeworks/vulmanjanos/3_conditionals_loops/rock_paper_scissors.py
> +    if player_1_option == player_2_option:
Emiatt a rész miatt, ha minden körben ugyanazt adják meg, akkor ez megy végbe:

```
How many round do you want to play?: 3
Player One, select an accepted option!: paper
Player Two, select an accepted option!: paper
It's a draw
Player One, select an accepted option!: paper
Player Two, select an accepted option!: paper
It's a draw
Player One, select an accepted option!: paper
Player Two, select an accepted option!: paper
It's a draw
That's all folks! The final result: Player One: 0 score, Játékos 2: 0 score
And the winner is Player Two!!!
```

Látod hogy akkor is azt írja hogy a kettes játékos nyer, ha amúgy a végeredmény döntetlen.
Ezt ki tudod küszöbölni a következőképp:


```
current_round = 1
    # for loopal meg kell határozni, hogy meddig játszanak és a játokosok válaszait pedig while loop-pal, if-else
while current_round <= accepted_round:
# for i in range(accepted_round):
    player_1_accepted = False
    while not player_1_accepted:
        player_1_option = input("Player One, select an accepted option!: " )
        if player_1_option in accepted_options:
            player_1_accepted = True
        else:
            print("This is not an accepted option, please choose a right one: ")
    player_2_accepted = False
    while not player_2_accepted:
        player_2_option = input("Player Two, select an accepted option!: ")
        if player_2_option in accepted_options:
            player_2_accepted = True
        else:
            print("This is not an accepted option, please choose a right one: ")
    # az eredmények kalkulásása helyes válasz esetén +1-gyel
    if player_1_option == player_2_option:
        print("It's a draw, repeat this round!")
        continue
    elif (player_1_option == "rock" and player_2_option == "scissors") or \
         (player_1_option == "paper" and player_2_option == "rock") or \
         (player_1_option == "scissors" and player_2_option == "paper"):
        points["Player One"] += 1
        print("Winner of the round : Player One")
    else:
        points["Player Two"] += 1
        print("Winner of the round : Player Two!")
    current_round+=1
```
Annyi változott, hogy van egy current_round változónk, és egy while loopra cseréltük a fort. Ha döntetlen van, akkor a `continue` újrajátszatja az aktuális kört addig amíg eltérő választ nem adnak. Ha eltérőt adnak, akkor a `current_round+=1` a végén gondoskodik arról, hogy a következő körre ugorjunk

2024-10-16 14:46 UTC, JanosV2 commented
Köszi. Módosítottam, lefutnak szépen, döntetlennél is. Felraktam újra, Remélem látható. Köszi.

2024-10-16 21:38 UTC, NagyIstvanGabor approved these changes
Szuper, köszi szépen! Approve-oltam, mehet a merge.

2024-10-17 11:27 UTC, merged