GaalIstvanTamas/Homework-3
Global-rd/python_hu pull request #128
Opened 2024-10-14 14:13 UTC by GaalIstvanTamas

2024-10-15 17:31 UTC, NagyIstvanGabor requested changes
Szia!

Szuper a házid, a második feladathoz írtam egy egyszerűsítési lehetőséget, hogy ne ismétlődjön a kódod. Odaírtam a részleteket. Ha ez megvan, megy is az approve.

Köszi szépen!

2024-10-15 17:31 UTC, NagyIstvanGabor commented on homeworks/gaalistvantamas/3_conditionals_loops/flat_finder.py
> +NEW_YORK_AND_SAN_FRANCISCO_LIMIT = 4000
szuperek a konstansok!

2024-10-15 17:31 UTC, NagyIstvanGabor commented on homeworks/gaalistvantamas/3_conditionals_loops/rock_paper_scissors.py
> +        print("Draw")
A teljes 32-38 sort amit ismételsz lecserélheted ennyivel:

`continue`

ezzel szimplán döntetlen esetén újrakezdjük az aktuális kört (mivel a continue nem engedi hogy a rounds += 1 lefusson.

2024-10-16 18:47 UTC, GaalIstvanTamas commented on homeworks/gaalistvantamas/3_conditionals_loops/rock_paper_scissors.py
> +        print("Draw")
Rövidítve, köszi a javaslatot, így könnyebb volt megérteni a "continue"-t. :)

2024-10-16 21:38 UTC, NagyIstvanGabor commented on homeworks/gaalistvantamas/3_conditionals_loops/rock_paper_scissors.py
> +        print("Draw")
Ennek örülök! Köszi :)

2024-10-16 21:39 UTC, NagyIstvanGabor approved these changes
Szuper, köszi szépen a változtatásokat! Approve-oltam, mehet a merge.

2024-10-17 05:19 UTC, merged