3rd homework
Global-rd/python_hu pull request #129
Opened 2024-10-14 14:32 UTC by DanTar93

Szia István!
Küldöm a 3. házi feladatomat.

Üdv,
Dani

2024-10-16 21:49 UTC, NagyIstvanGabor requested changes
Szia!

Szuper a házid, 1-1 apróság van mind a két feladatban amit javíts kérlek. Ha ezek megvannak, megy is az approve. Köszi szépen!

2024-10-16 21:49 UTC, NagyIstvanGabor commented on homeworks/taridaniel/3_conditionals_loops/flat_finder.py
> +if (city == "New York" or city == "San Francisco") and price < 4000:
Nem hiba, csak rövidítési lehetőség:

`if city in ["New York", "San Francisco"] and price < 4000:`

2024-10-16 21:49 UTC, NagyIstvanGabor commented on homeworks/taridaniel/3_conditionals_loops/flat_finder.py
> +elif (city != "New York" or city != "San Francisco" or city != "Washington" or city != "Chicago") and price <= 3000:
`(city != "New York" or city != "San Francisco" or city != "Washington" or city != "Chicago") and`

Ez a rész ebbe a feltételbe már nem kell. Ha idáig eljut a végrehajtás, akkor biztosak lehetünk benne hogy a city nem ezen városok valamelyike, mert előtte már mindegyiket megvizsgáltad. Elég annyi hogy ha az árat megvizsgálod hogy 3000 alatt van e.

2024-10-16 21:49 UTC, NagyIstvanGabor commented on homeworks/taridaniel/3_conditionals_loops/rock_paper_scissors.py
> +        print("It's a tie!")
Ezzel az a gond, hogy ha mindhárom kör döntetlen, akkor a játék is döntetlen lesz.
A kódod viszont azt írja ki hogy:
`Player 2 wins by 0 points!`

Mert a végén nem kezeled a döntetlen lehetőségét, csak hogy egyiküknek több pontja van e a másiknál (40-43 sorok).
Vagy kezeld le a végén a döntetlent, vagy ha életszerűbbre szeretnéd a játékot, akkor igazából egy kör se térhet véget amíg ugyanazt az input-ot adják. Ezt röviden megoldhatod így:
```

possible_choices = ["rock", "paper", "scissors"]
current_round = 1
# Play the game for a certain number of rounds
while current_round <= rounds:
#for word in range(rounds):
    while True:
        player1_choice = input("Player 1, enter your choice (rock, paper, or scissors): ")
        if player1_choice in possible_choices:
            break
        else:
            print("Error: Invalid choice. Please enter rock, paper, or scissors.")

    while True:
        player2_choice = input("Player 2, enter your choice (rock, paper, or scissors): ")
        if player2_choice in possible_choices:
            break
        else:
            print("Error: Invalid choice. Please enter rock, paper, or scissors.")

    if player1_choice == player2_choice:
        print("It's a tie, try this round again!")
        continue
    elif (player1_choice == "rock" and player2_choice == "scissors") or \
         (player1_choice == "scissors" and player2_choice == "paper") or \
         (player1_choice == "paper" and player2_choice == "rock"):
        player1_points += 1
    else:
        player2_points += 1
    
    current_round += 1

```

ami itt történt: 
1. bevezettem egy current_round változót, ami a körök számát fogja track-elni.
2. a for loopot lecseréltem egy while loopra, addig loop-olunk amíg a current_round ami 1-től kezdődik, eléri a rounds-ot.
3. Ha döntetlent játszanak, akkor a continue-val újrakezdjük a kört. Azért kezdődik újra a kör, mert így nem jut el a kód a loop végére, ahol növelnénk a current_round értékét 1-gyel. Így addig megy minden kör amíg eltérő input-ot nem adnak meg, és nem kell a döntetlent lekezelned a végén egy plusz condition-nel.

2024-10-17 12:24 UTC, DanTar93 commented
Szia István!
Köszönöm az észrevételeidet és a segítséget! Alakítottam a kódjaimon a leírtak alapján.

2024-10-17 17:52 UTC, NagyIstvanGabor approved these changes
Köszi szépen, approve-oltam is. Mehet a merge.

2024-10-17 20:16 UTC, merged