Debreczenizoltan/homework 2
Global-rd/python_hu pull request #135
Opened 2024-10-21 06:45 UTC by DebZol

próbálgatás

2024-10-23 09:13 UTC, NagyIstvanGabor requested changes
Szia!

Ez a kettes házihoz így szuper, csak a .gitignore-ból ezt a sort töröld kérlek:
![image](https://github.com/user-attachments/assets/10b09f6e-bcd0-47a7-bcfd-a4e7d0830074)

`lessons/04/proba.py`
Ha ez megvan, approve-olom is. Köszi.

2024-10-26 18:17 UTC, NagyIstvanGabor requested changes
Szia!

Egyetlen apróság marad még bent, hozzáadsz egy üres sort a .gitignore-hoz.
Kitörölted ugye amit kértem, ez szuper, de ezt az üres sort is töröld kérlek.
Ha ez megvan megy is az approve. Köszi szépen!
![image](https://github.com/user-attachments/assets/03073e6c-64ac-4f15-bf12-9786a5108909)

2024-10-28 20:03 UTC, NagyIstvanGabor submitted a review, later dismissed
Köszi, approve-oltam. Mehet a merge.

2024-10-30 07:47 UTC, NagyIstvanGabor submitted a review, later dismissed
Approve-oltam, köszi. Mehet a merge.

2024-10-30 07:50 UTC, NagyIstvanGabor approved these changes
-

2024-10-30 07:51 UTC, nistvangabor submitted a review, later dismissed
-

2024-10-30 08:12 UTC, nistvangabor approved these changes
Szia!

Volt egy kis fennakadás a PR-oddal, mert időközben hozzáadtam egy változtatást a .gitignore-hoz, és még a tiédben is bent volt egy whitespace változtatás, amit eredetileg jóvá akartam hagyni mert nem okozott volna gondot. Így egy kicsit segítettem, hogy megoldódjon a probléma. (Te alapból is jól csináltad, de nem akartam megbonyolítani a dolgod extra teendőkkel). 
Approve-oltam ezt a verziót, mehet is a merge. Köszi szépen!

2024-10-30 08:19 UTC, merged