to_do.py
Global-rd/python_hu pull request #143
Opened 2024-10-24 15:45 UTC by barnaf03

Szia! Ebben van egy txt fájl, ami tartalmazza azokat, amiket beleírtam, de a fő problémám, hogy nem érti, hogy hol van a file path. Van, amikor le se fut a program... Szóval eléggé tétlenül ülök.

2024-10-25 16:33 UTC, NagyIstvanGabor requested changes
Szia!

Gyakorlatilag csa ka file_path változóval van probléma, ezért nem úgy fut le a kódod ahogy szeretnéd. Erre Discord-on részletes visszajelzést adtam, kérlek olvasd el. Ott le is írtam hogy kéne kinézzen a file_path változó és miért.

Nincs szükség semmire azon kívül, hogy a file_path-et helyesen megadod. Ezután gyakorlatilag a következő sor már a read_tasks() function definiálása kell legyen. Erről is van egy screenshot Discord-on.

Ne add fel, mert a megoldásod egyébként szuper! :)
Csak néhány apróság van amit konkrétan a megoldással kapcsolatban kértem mint változtatás, azokat nézd át kérlek.
Illetve még egy dolog: ha kész vagy, akkor ezt a mappa struktúrát hogy python_rd_repo/python_hu töröld, illetve a root-ban lévő tasks.txt-t is. Minden csak a saját mappádon belül legyen.

2024-10-25 16:33 UTC, NagyIstvanGabor commented on homeworks/feherbarnabas/4_exceptions_logging/to_do.py
> +# Üres .txt fájl létrehozása
Erre a részre nincs szükség. Amint egy feladat hozzáadását választja a user, létre fog jönni a file magától.

2024-10-25 16:33 UTC, NagyIstvanGabor commented on homeworks/feherbarnabas/4_exceptions_logging/to_do.py
> +# A fájl létrehozása
Erre a részre nincs szükség. Amint egy feladat hozzáadását választja a user, létre fog jönni a file magától.

2024-10-25 16:33 UTC, NagyIstvanGabor commented on homeworks/feherbarnabas/4_exceptions_logging/to_do.py
> +file_path = "python_rd_repo/python_hu/homeworks/feherbarnabas/4_exceptions_logging/tasks.txt"
Erre reagáltam Discord-on, kérlek olvasd el. A file path így kell kinézzen:
`file_path = "homeworks/feherbarnabas/4_exceptions_logging/tasks.txt"`

2024-10-25 16:33 UTC, NagyIstvanGabor commented on homeworks/feherbarnabas/4_exceptions_logging/to_do.py
> +os.makedirs(os.path.dirname(file_path), exist_ok=True)
Ez sem kell.

2024-10-25 16:33 UTC, NagyIstvanGabor commented on homeworks/feherbarnabas/4_exceptions_logging/to_do.py
> +def remove_task(task):
A remove tasks szuper lenne ha kiírná a jelenlegi task-okat, hogy a felhasználó lássa miket tud törölni.

2024-10-26 18:51 UTC, barnaf03 commented
Hogyan kell ezeket törölni?

2024-10-26 19:26 UTC, barnaf03 commented
Feltaláltam magam.

2024-10-26 19:27 UTC, barnaf03 commented
Illetve, köszönöm a segítséget! Nem tudom, hogy ezek után érdemel-e ez max pontszámot, de sokat tanultam belőle.

2024-10-28 20:08 UTC, NagyIstvanGabor approved these changes
Szia!

Nagyon örülök, hogy simán megoldottad egyedül! Érdemel max pontszámot, mert határidőn belül egy merge-ölhető verziót hoztál össze. Nem arra adok max pontot, ha valaki egyből hibátlan feladatot ad le (ilyen nem sokszor fordul elő), hanem ha valaki beleteszi a munkát és reagál a visszajelzésekre ;)
Köszi szépen, mehet a merge.

2024-10-28 20:10 UTC, merged