karolinavalko/homework4
Global-rd/python_hu pull request #144
Opened 2024-10-24 16:28 UTC by KarolinaValko

Szioka!

Ismet egy izgi feladat. En is sokat olvasok utana, meg nezegetem neten, illetve brainstormolok csaladilag. 

4 file van:
- a to_do lista txt-ben
- to do lista jsonben
- az ures txt
- illetve egy ini file. Ezt neten olvastam, hogy igy egy kicsit szebbe lehet varazsolni a kodot, ha nem mindent egy helyre rakok
- a gitignor nekem mar eredetileg is megvolt a legelsö main copy utan. Megneztem, benne van a *.log szoval nem nyultam hozza

A log jol muködik, szepen irja vissza mi törtent, mikor stb. Volt egy erdekes dolog, amikor ketszer irta ki a logot egymas utan a terminalra, de aztan kis utanaolvasas utan a propagate = 0 megoldotta a dolgot ;-) csak gondoltam leirom mert ez erdekes volt.

Varom a visszajelzesed, eszreveteleid!

Szep estet!

Karolina

2024-10-25 17:23 UTC, NagyIstvanGabor requested changes
Szia!

Ismét szuper a házi, hagytam néhány megjegyzést apró javítani valókról. Profi az .ini file használat a logging-hoz!

2024-10-25 17:23 UTC, NagyIstvanGabor commented on homeworks/karolinavalko/4_exceptions_logging/json_to_do.py
> +    except:
szuper, hogy kezeled a váratlan eseményeket is, de itt adhatnál visszajelzést arról, hogy pontosan miért nem lehet beolvasni a file-t, ha hivatkozol is magára az Exception-re:
```
...
except Exception as e:
    logger.error(f"The file {file_path} could not be read: {e}.")
```

2024-10-25 17:23 UTC, NagyIstvanGabor commented on homeworks/karolinavalko/4_exceptions_logging/to_do.py
> +logging.config.fileConfig(
ugyanazok a dolgok igazak itt is, amit a json-ös megoldáshoz írtam (relative path, nem kell raw string, forward slash-ek)

2024-10-25 17:23 UTC, NagyIstvanGabor commented on homeworks/karolinavalko/4_exceptions_logging/to_do.py
> +    except:
Szerintem itt csak lemaradt, mert a json-ös megoldásban kezeled: ne használ sima exception-t, kezeld külön külön azokat a helyzeteket amikre fel vagy készülve (FileNotFoundError, esetleg OSError, IOError), és except Exception as e-vel a váratlan helyzeteket.

2024-10-25 17:23 UTC, NagyIstvanGabor commented on homeworks/karolinavalko/4_exceptions_logging/json_to_do.py
> +    except IndexError as e:
itt a try-ban meg lehetne vizsgálni, hogy a to_do_list üres e, és ha az, akkor nem is kéne hagyni a felhasználót megpróbálni törölni valamit, mert úgyis IndexError lesz a vége.

2024-10-25 17:23 UTC, NagyIstvanGabor commented on homeworks/karolinavalko/4_exceptions_logging/to_do.py
> +def write_list(file_path, list):
Ne használd kérlek a "list" elnevezést paraméterként. Itt most nem okoz hibát, mert nem használod a list() konstruktort a function-ön belül, de bad practice python keyword-öket használni változónevekhez.
`task_list`, vagy bármi más leíró név mehet.

2024-10-25 17:23 UTC, NagyIstvanGabor commented on homeworks/karolinavalko/4_exceptions_logging/json_to_do.py
> +while True:
ez az egész loop bekerülhetne egy main() function-be, ezzel jelezve hogy ez a kódod kiinduló pontja.

2024-10-25 17:23 UTC, NagyIstvanGabor commented on homeworks/karolinavalko/4_exceptions_logging/to_do.py
> +    except IndexError as e:
ugyanaz a story mint fentebb, szuper lenne megvizsgálni hogy üres e a lista

2024-10-25 17:23 UTC, NagyIstvanGabor commented on homeworks/karolinavalko/4_exceptions_logging/to_do.py
> +def write_list(file_path, list):
Ne használd kérlek a "list" elnevezést paraméterként. Itt most nem okoz hibát, mert nem használod a list() konstruktort a function-ön belül, de bad practice python keyword-öket használni változónevekhez.
task_list, vagy bármi más leíró név mehet.

2024-10-25 17:23 UTC, NagyIstvanGabor commented on homeworks/karolinavalko/4_exceptions_logging/to_do.py
> +    except:
Szerintem itt csak lemaradt, mert a json-ös megoldásban kezeled: ne használ sima exception-t, kezeld külön külön azokat a helyzeteket amikre fel vagy készülve (FileNotFoundError, esetleg OSError, IOError), és except Exception as e-vel a váratlan helyzeteket.

2024-10-25 17:23 UTC, NagyIstvanGabor commented on homeworks/karolinavalko/4_exceptions_logging/to_do.py
> +logging.config.fileConfig(
ugyanazok a dolgok igazak itt is, amit a json-ös megoldáshoz írtam (relative path, nem kell raw string, forward slash-ek)

2024-10-25 17:23 UTC, NagyIstvanGabor commented on homeworks/karolinavalko/4_exceptions_logging/json_to_do.py
> +    except:
szuper, hogy kezeled a váratlan eseményeket is, de itt adhatnál visszajelzést arról, hogy pontosan miért nem lehet beolvasni a file-t, ha hivatkozol is magára az Exception-re:

```
...
except Exception as e:
    logger.error(f"The file {file_path} could not be read: {e}.")
```

2024-10-25 17:23 UTC, NagyIstvanGabor commented on homeworks/karolinavalko/4_exceptions_logging/json_to_do.py
> +file_path = r"c:\Users\tabal\OneDrive\ドキュメント\python_hu\homeworks\karolinavalko\4_exceptions_logging\to_do.json"
itt is relative path lesz a jó megoldás, említettem fent.

2024-10-25 17:23 UTC, NagyIstvanGabor commented on homeworks/karolinavalko/4_exceptions_logging/json_to_do.py
> +logging.config.fileConfig(
Az absolute path-ek ebben az esetben nem a legmegfelelőbbek, mivel ha én ezt le szeretném futtatni, nem lenne meg az elérési útvonal a gépemen. Használj kérlek relative path-et.
Nem szükséges raw string-et használni a path-eknél (r betű a string előtt, ez azt csinálja hogy a backslash-eket ignorálja, és nem tekinti escape characternek, szóval pl a \n nem fog új sort kezdeni). Simán használhatsz szokásos string-et forward slash-ekkel:

logging.config.fileConfig("homeworks/karolinavalko/4_exceptions_logging/logger_set_up.ini")
(ez azt feltételezi hogy a cwd a project root-ja.)
Ez igaz az összes path-re amit megadtál (13. sor)
Nagyon szuper amúgy hogy utánanéztél az .ini-s file setup-nak! Fogunk erről tanulni amikor már áttérünk a projekt fókuszúbb órákra, neked már nem lesz új :)

2024-10-25 17:23 UTC, NagyIstvanGabor commented on homeworks/karolinavalko/4_exceptions_logging/json_to_do.py
> +        return []
szuper hogy hiba esetén visszaadsz egy üres listát, de ez most jelenleg csak akkor teljesül ha az a gond hogy nincs meg a file. Ha valami váratlan hiba történik amit eggyel lejjebb kezelsz, ott nem returnölsz üres listát.
Áttehetnéd ezt a return []-t a function legvégére, és akkor bármelyik exception történik, a function-öd üres listát ad vissza, nem None-t.

2024-10-25 17:23 UTC, NagyIstvanGabor commented on homeworks/karolinavalko/4_exceptions_logging/to_do.py
> +def read_file(file_path):
ebben a function-ben is szuper lenne visszaadni egy üres listát ha valami hiba történik.

2024-10-26 19:28 UTC, KarolinaValko commented
Köszönöm szepen az eszreveteleket! Javitottam mindent! :-)

2024-10-28 20:10 UTC, NagyIstvanGabor approved these changes
Szia! Nagyon szépen köszi a változtatásokat! Így már szuper minden, approve-oltam is. Mehet a merge.

2024-10-29 07:46 UTC, merged