4. Házi feladat
Global-rd/python_hu pull request #153
Opened 2024-10-27 23:19 UTC by szabig

Elkészült az első verziója.

A .gitignore-ba ennyit írtam csupán: Task_Manager_logs.log
Ennyi elég? Mert látom itt a PR-emben az írja rá, hogy "empty file".
Elrontottam valamit az lehet?

2024-10-29 16:13 UTC, NagyIstvanGabor requested changes
Szia!

A feladatmegoldásod szuper, egyetlen egy változtatást kértem csak be a .gitignore-ral kapcsolatban, ehhez odaírtam a részleteket kommentben. Köszi szépen!

2024-10-29 16:13 UTC, NagyIstvanGabor commented on homeworks/szabolcsgesztesi/4_exceptions_logging/.gitignore
> +Task_Manager_logs.log
Nem írja hogy empty file, itt van a Task_Manager_logs.log
Viszont a feladat megfogalmazása egy kicsit becsapós volt :) A .gitignore már alapból jelen van a repository root-jában:
https://github.com/Global-rd/python_hu/blob/main/.gitignore

Ebben a file-ban már ott van ez a sor:
https://github.com/Global-rd/python_hu/blob/880967aeb5b44c7c5e3b1a2c72c19177bebdf4ac/.gitignore#L21

a *.log-ban a * egy ún. wildcard, ami azt jelenti hogy minden file-t ami .log kiterjesztésű, ki fog zárni a verziókezelésből. Beleértve ebbe az almappákban lévő log file-okat is. Így neked külön nem kell egy .gitginore a mappádba, ezt töröld kérlek.

2024-11-02 15:37 UTC, szabig commented
Kitöröltem az alkönyvtárban lévő .gitignore-t, ahogy kérted, így a root-ban lévő fogja kizárni a *.log-okat.

2024-11-02 21:01 UTC, szabig commented
Ja, közben az 5. Házival is elkészültem. Miután Commitoltam egyet a GitHub Desktopban, csodálkoztam is, hogy nem ajánlotta fel a Push requestet. Most látom, hogy az arra rányomott Commitom, is ugyanebbe a Push Requestbe ment bele, mert már van egy nyitva. :) Legalább megtudtam, hogy ez hogy működik. Jól értettem/csináltam?

2024-11-05 07:37 UTC, NagyIstvanGabor requested changes
Szia!

Igen, ha még van nyitva PR-od, és ugyanazon a branch-on vagy, akkor a push update-eli a meglévő PR-t.
Azt most vettem csak észre én is (ezért elnézést kérek), hogy a 4-es házit és az 5-ös házit is egy homework-1 nevű branch-ről csináltad. Mivel a 4-es még nem volt bemerge-ölve amikor már az 5-öst is push-oltad, ezért bekerült az 5-ös házid is ide.

Ez így azért nem a legjobb, mert a valóságban ez a 4-es és 5-ös házi két különböző feature, és a branch nevének tükröznie kéne hogy mit tartalmaz. Így ugye ez nem történik meg mert egy homework-1 nevű branchről próbáljuk most bemerge-ölni a 4-es és 5-ös házit :).
Na de semmi gond, a 4-es házi mostmár maradjon a homework-1 branch-en. Szuper hogy innen törölted a .gitignore-t, így a 4-es házid már merge-ölhető.
Az 5-ös mappát másold ki átmenetileg valahova (pl az asztalodra), majd töröld erről a branch-ről úgy ahogy van. Ezután commit, push. Ha ez megvan akkor approve-olom a 4-est.
Ezután menj át a main-re, fetch, pull. Ha megvan, akkor hozz létre egy új branch-et a main alapján (szabolcsgesztes/homework-5). Másold be ide az asztalról az 5-ös házid mappáját, és commit push. Majd nyiss egy PR-t erről a branch-ról az 5-ös házinak.
Így el tudod szeparálni őket, és a jövőben is mindig így csináld kérlek. Minden házi új branch, és akkor nem íródik felül az előző.

Az 5-ös házid nagyon szép munka, örülök hogy ilyen szuperül elsajátítottad az OOP-t, ez később nagyon fontos lesz. Nem kérek semmi változtatást ezzel kapcsolatban. Köszi szépen.

2024-11-09 09:58 UTC, szabig commented
Juj valóban! Mindegyiket egy branch-en belül csináltam, upsz!
Rendben akkor most kitöröltem az 5-ös házit, és ha elfogadod akkor bemergelem, majd létrehozom az új branch-et és feltöltöm oda!

Akkor csak egy kérdés: Az új branch létrehozásánál mindig a "main"-re hivatkozva hozzam létre, ugye?

Köszönöm!

2024-11-09 10:53 UTC, NagyIstvanGabor approved these changes
Szia!

Ez így már szuper, approve-oltam is. Igen, új branch-et mindig a main alapján hozz létre.
Nem kell megvárni vele amíg bemerge-ölöd a 4-est (persze megteheted) de mivel két különböző részét módosítod a kódbázisnak, ezért függetlenek egymástól.
Várom a PR-t az 5-ösre, köszi.

2024-11-09 11:34 UTC, merged