editerdelyhorvath/homework_5
Global-rd/python_hu pull request #167
Opened 2024-11-02 21:57 UTC by NyugtonMalac

- **car_fleet_mgr.py** flotta kezelő alkalmazás fejlesztése: elvégzi a feladatkiírásban kért műveleteket és esztétikusan megjeleníti.

- a **requirements.txt** file kiegészítése az általam használt colorama modul telepítése miatt. Ezt a printelésnél használt színnel való kiemelésre használtam.

- a szükséges kiszolgáló file-ok létrehozása: 

    - **LoggerSettingsForHomeworks.py** -» a loggereket ne kelljen mindig megírni, csak paramétereket kelljen megadni a main file-okban. 
    - **exception_handling_to_classes.py** -» InvalidAmountError egyedi hibaüzenetek használáshoz 
    - **car.py** -» a car objektumok létrehozásához, vezetéséhez és tankolásához 
    - **fleet.py** -» flotta kezeléshez: car objektum hozzáadásához, elvételéhez, információk megjelenítéséhez.

A programkódba beégettem a car objektumokat, és a működésüket. További fejlesztési lehetőség lenne, hogy ezeket a felhasználó adja meg és eltároljuk valahol.

Logolás a consolra és a **logs/car_fleet_log.log** file-ba történik, amelynek a helye az a mappa, ahol a car_fleet_mgr.py file is található. Ha a mappa/file nem létezik, létrehozza. Ezt nem tartalmazza a Branch.

A Logokat személyre szabtam, hogy felhasználóbarát legyen az olvasása (nekem tetsző módon).

2024-11-11 13:01 UTC, NyugtonMalac commented on homeworks/editerdelyhorvath/_0_Functions/car.py
> +        if self.logger:
Itt is implementálva a változtatás.

2024-11-11 13:39 UTC, NyugtonMalac commented on homeworks/editerdelyhorvath/_0_Functions/car.py
> +        self.name = name
A name paramétert az autók egyedi azonosítására használtam (ugyan így a Fleet osztályban is) ez alapján jelenítem meg az autók információit, például car1, car2 formában.

Javaslatra beépítettem az automatikusan létrehozott ID használatát.

2024-11-11 13:39 UTC, NyugtonMalac commented on homeworks/editerdelyhorvath/_0_Functions/car.py
> +        self.brandbrand = brand
Köszönöm szépen, ezt nem vettem észre :O

2024-11-11 13:41 UTC, NyugtonMalac commented on homeworks/editerdelyhorvath/_0_Functions/exception_handling_to_classes.py
> +        super().__init__(message)
javítottam, köszönöm az észrevételt.

2024-11-12 10:33 UTC, NagyIstvanGabor approved these changes
Köszi szépen a változtatásokat, approve-oltam is. Mehet a merge.

2024-11-12 12:36 UTC, NyugtonMalac commented
@NagyIstvanGabor,

Nagyon szépen köszönöm, szeretném merge-ölni, de nincs lehetőségem:
<img width="893" alt="image" src="https://github.com/user-attachments/assets/cf0b896a-b8cc-439e-921b-93a6c835074e">

Mit tegyek?

Köszönöm!
Edit

2024-11-14 09:28 UTC, NagyIstvanGabor approved these changes

2024-11-14 09:29 UTC, NagyIstvanGabor commented
> @NagyIstvanGabor,
> 
> Nagyon szépen köszönöm, szeretném merge-ölni, de nincs lehetőségem: <img alt="image" width="893" src="https://private-user-images.githubusercontent.com/182530390/385285075-cf0b896a-b8cc-439e-921b-93a6c835074e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NzY4MDIsIm5iZiI6MTczMTU3NjUwMiwicGF0aCI6Ii8xODI1MzAzOTAvMzg1Mjg1MDc1LWNmMGI4OTZhLWI4Y2MtNDM5ZS05MjFiLTkzYTZjODM1MDc0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQwOTI4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjNiOTVkYmU0N2M5N2M1Y2NjNWFhN2YwZTY3Zjc5YWZmY2FiZTc3MDgwYzA5NzAyYTQxZjkyNTgzN2Q5YzAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Z1dHjDLkcgYJrxGHZwF_Xn1LIADnH4kZlGxHLxrKhpI">
> 
> Mit tegyek?
> 
> Köszönöm! Edit

Szia!

Approve-oltam újra, most jó kell legyen. Köszi!

2024-11-15 18:38 UTC, NyugtonMalac commented
Bementem a Resolve conflicts-ba, csak egy üres sor volt a requirements.txt-ben és azt írta, nulla conflicts. Volt lehetőség a merge gombra kattintani, majd most megint itt vagyunk. 

Hogy kell ebből kilábalni? Ki kellene vennem a requirements.txt-t a branch-ből?

Köszönöm a segítséget és bocsánat, hogy már 3adszorra tartunk ugyan ott.
Edit

2024-11-15 19:04 UTC, NagyIstvanGabor approved these changes

2024-11-15 19:09 UTC, NagyIstvanGabor requested changes
Szia!

Most ugyan azt írja, ha approve-olnám, hogy nincs conflict, de ezzel kitörölnél mindent ami a requirements.txt-ben van most a main-en:
![image](https://github.com/user-attachments/assets/a616a19e-d3c2-4ac2-88f4-25921a0d942a)
Valószínűleg azért volt conflict-od, mert változott időközben a requirements.txt tartalma a main-en (hozzá lett adva a pandas, a pytest stb.) és neked ugyanazokon a sorokon más dependency-k voltak felsorolva. 
Ilyenkor a megoldás az, hogy akár vs code-ban akár itt githubon (ha kicsi a file) a conflciting file-t olyan verzióra hozod mint ami a main-en van.
A törlés helyett légyszi menj át a main-re, másold ki a requirements.txt tartalmát, majd gyere vissza a saját branch-edre és másold be ebbe a requirements.txt-be. Így ugyanaz a verzió lesz a gépeden mint a main-en, és el kéne tűnjön a változtatást. Köszi!

2024-11-16 09:07 UTC, NyugtonMalac commented
Szia István,

Köszönöm szépen, most remélem jó lesz. Izgalmas volt végigmenni egy conflict kezelésen is. Az első kezelésemnél egyszerűen mindent kitöröltem, így üres lett a requirements.txt-m, nem tudom, hogy lett üres, mert nem csináltam vele semmit. Most ellenőriztem, hogy a colorama, amit én tettem volna bele, az benne van a main-ben is, így elég volt csak ugyanazt a file-t átmásolni nekem, ahogy írtad. 

Még egyszer köszönöm!

2024-11-16 09:07 UTC, NagyIstvanGabor approved these changes
Szia!

Így már szuper, egy newline character csak a különbség most a requirements.txt-ben, de ez nem okoz semmi problémát. Approve-oltam, mostmár tényleg mehet a merge :)

2024-11-16 09:26 UTC, merged