nagybalazs/homework-5
Global-rd/python_hu pull request #169
Opened 2024-11-04 06:11 UTC by balanagy23

2024-11-05 10:16 UTC, NagyIstvanGabor requested changes
Szia!

Nagyon profi a házi, szuperül elsajátítottad az OOP-t. Néhány apróságot jeleztem csak kommentben, nézd át ezeket kérlek. Köszi szépen!

2024-11-05 10:16 UTC, NagyIstvanGabor commented on homeworks/nagybalazs/5_oop/car_fleet_mgr.py
> +    def refuel(self, amount):
itt szuper lenne ellenőrizni hogy a felhasználó nem e adott meg negatív értéket.

2024-11-05 10:16 UTC, NagyIstvanGabor commented on homeworks/nagybalazs/5_oop/main.py
> +class Fleet:
Szuper hogy szétszedted külön modulra a main-t, ahol használod a class-ok kódját, és magát a Car class definícióját.
Lehetne ez a Fleet class is egy külön fleet.py-ban, a Car pedig egy car.py-ban. és ezeket importálhatnád a main.py-ba ahol csak a main() van.
Ezzel még jobban elszeparálnád logikailag az elemeket.

2024-11-05 17:45 UTC, balanagy23 commented
Köszönöm a dicséretet de kb 20 óra volt mire sikerült megcsinálnom :) szerintem az egy kicsit sok. :) Viszont a végére valóban sikerült megértenem talán és terméseztessen nagyon jól magyaráztad el!

2024-11-06 19:31 UTC, NagyIstvanGabor approved these changes
Szia!

A 20 óra 2x1.5 óra előadás alapján egy ilyen feladatra teljesen rendben van. Az alapokba érdemes beleölni az időt, később kifizetődik majd.
Approve-oltam is, mehet a merge. Köszi szépen!

2024-11-07 19:03 UTC, merged