Homework-1 SchBalázs
Global-rd/python_hu pull request #17
Opened 2024-09-24 15:10 UTC by snerbalu

2024-09-24 15:26 UTC, NagyIstvanGabor requested changes
Szia!

A homeworks/schreinerbalazs/main.py-ból hiányzik egy adattípus. Nézd vissza hogy melyikről tanultunk még és add hozzá légyszi.

A pull request-nek csak a homework mappába való változtatásokat szabad tartalmaznia, a lessons mappába csak én fogok változtatásokat push-olni (itt az órai anyagok lesznek). Ezeket töröld légyszi (main.py hozzáadása és test.py változtatása).

Ha megvan minden, jöhet a git push.

2024-09-24 16:45 UTC, NagyIstvanGabor requested changes
Szia!

Szuper, a string hiányzott.
Igen, eredetileg rossz mappában volt a main.py, látom ezt is javítottad, köszi.

Bent hagytad viszont a pull request-ben azt a main.py-t ami simán a schreinerbalazs mappában van, illetve még mindig ott van a main.py és a test.py a lessons-ben.
Töröld ki a schreinerbalazs/main.py file-t, a lessons/02/main.py-t, és a változtatásodat a lessons/02/test.py-ból. Commit, push és kész is vagy.

![files_to_drop](https://github.com/user-attachments/assets/ffe49fef-9353-4621-a28f-66e8415dbb5b)

2024-09-24 17:00 UTC, NagyIstvanGabor commented
Szia! Majdnem jó, elhamarkodottan fogalmaztam a test.py törlésével :) Azóta pontosítottam de szerintem nem olvastad.
Mivel a test.py-t nem hozzáadtad, hanem módosítottad, ezért annál a módosítás törlésére gondoltam, nem a teljes file törlésére.
Tettem is egy screenshot-ot a felső kommenthez, ahol látod hogy kell a test.py print("test") tartalommal. Így lesz szinkronban a lessons mappa a remote-tal, és lesz csak a homework-ös változtatásod jelen a PR-ban.

2024-09-25 06:27 UTC, snerbalu commented
Köszönöm, ilyenkor mi a helyes eljárás?
Tegyem be vissza ezeket a fájlokat a gépemen a könyvtárba?

2024-09-25 08:42 UTC, nistvangabor commented
> Köszönöm, ilyenkor mi a helyes eljárás? Tegyem be vissza ezeket a fájlokat a gépemen a könyvtárba?

Amikor több file-ról van szó és összetettebb a dolog, akkor az eljárás elég bonyolult (létrehozni a master-ből egy új branch-et, checkout-olni a mostanin azt a commit-ot ami tartalmazza a változtatást amire szükséged van, cherry picking stb., ezek elég haladó szintű témák.).

Jelen esetben ha a [lessons/02/test.py](https://github.com/Global-rd/python_hu/pull/17/files#diff-02185f726f65456da7d02e3122bc15bf8e6c410bc0283df5f1920b2511511689)-ba visszaírod hogy print("test"), azzal visszaszinkronizálod a branched a main-nel, és már csak a házi feladatot marad az egyetlen változtatás.
Figyeld felül a Files Changed fület, ha az 1-re vált, és az a házid, akkor kész is vagy.

2024-09-25 12:13 UTC, nistvangabor commented
Szia!

Az utolsó commit-odban csak a main.py-ban írtad át a string értékét (egyébként bármikor szívesen segítek :)).
![image](https://github.com/user-attachments/assets/c624711a-8615-4304-8bab-26013e0c6da7)
a test.py még mindig hiányzik. A lényeg hogy legyen a branch-eden a lessons-ben egy 02 nevű mappa, amiben van egy test.py nevű python file. Ennek a tartalma az első soron annyi legyen hogy print("test"). Ez az amit véletlenül kitöröltél, ha ezt visszarakod onnantól megleszünk.

Azért nem tudom ezt így jóváhagyni, mert ezzel kitörölnénk ezt az órán létrehozott file-t a master-ben is.

2024-09-25 13:14 UTC, NagyIstvanGabor approved these changes
LGTM, Kibogoztad a szálakat! :) Max pont, mehet a merge.

2024-09-26 08:07 UTC, merged