gaalistvantamas/homework-4
Global-rd/python_hu pull request #170
Opened 2024-11-04 11:36 UTC by GaalIstvanTamas

Elnézést a késésért.

2024-11-05 10:26 UTC, NagyIstvanGabor requested changes
Szia!

Semmi gond, köszi szépen hogy elküldted. Szép munka, néhány apró visszajelzést írtam csak. Nézd át kérlek.
A pontjaid sajnos most nem tudom utólag módosítani, de ha legközelebb esetleg egy kicsivel több időre van szükséged, jelezd kérlek nekem privátban Discord-on, figyelembe fogom venni, és ebben az esetben a pontokat is tudom utólag igazítani. 
Köszi szépen!

2024-11-05 10:26 UTC, NagyIstvanGabor commented on homeworks/gaalistvantamas/4_exceptions_logging/to_do.py
> +    logger.info(f"Task {removable_task} is removed!")
Ez itt akkor is kiírja hogy task is removed, ha amit megadtam nincs is a listában. Ezt a visszajelzést inkább a 71. soron írd ki, ahol ténylegesen megtörténik a törlés.

2024-11-05 10:26 UTC, NagyIstvanGabor commented on homeworks/gaalistvantamas/4_exceptions_logging/to_do.py
> +            removable_task = input("Please give a name of the task that you want to delete!\n")
szuper lenne, ha itt látnánk, hogy milyen feladatok vannak jelenleg a listában, hogy tudjuk mikből lehet választani.
lehetne pl egy list_task() function amit itt meghívsz, és kiprinteli a jelenlegi feladatokat.

2024-11-05 10:26 UTC, NagyIstvanGabor commented on homeworks/gaalistvantamas/4_exceptions_logging/to_do.py
> +def view_task():
A view_task()-ban szuper lenne egy visszajelzés, ha üres a lista.

2024-11-05 21:39 UTC, GaalIstvanTamas commented
Elkészítettem a változásokat, amit kértél. Még a listából kiszedésnél is kivettem a felesleges vesszőket. :)

2024-11-06 19:32 UTC, NagyIstvanGabor approved these changes
Köszi szépen! Approve-oltam is, mehet a merge.

2024-11-06 20:44 UTC, merged