feherbarnabas/homework_5
Global-rd/python_hu pull request #175
Opened 2024-11-04 20:25 UTC by barnaf03

2024-11-04 20:25 UTC, barnaf03 commented
Szia! Valahogy hozzáadtam a 4. házi programját is először, de reményeim szerint most már minden rendben van.

2024-11-05 10:45 UTC, NagyIstvanGabor requested changes
Szia!

Nagyon szépen használod az OOP alapjait. Magával a házival kapcsolatban csak egy apró visszajelzésem van, a negatív refuel()-hez, odaírtam kommentben a részleteket.
A PR-odban törlöd a to_do.py-t a 4-es házidból, ezt kérlek másold vissza a main branch-ből hogy ne tekintse delete-nek (a branch-on amiről nyitottad ezt a PR-t nincs jelen ez a file).
![image](https://github.com/user-attachments/assets/0de5d7c9-430a-4492-b7e9-c3216d69228c)
![image](https://github.com/user-attachments/assets/a341d8ad-cdcf-4d3d-8e7a-6011b1ebd523)

2024-11-05 10:45 UTC, NagyIstvanGabor commented on homeworks/feherbarnabas/5_oop/car_fleet_mgr.py
> +    def refuel(self, amount):
szuper lenne megvizsgálni hogy a felhasználó nem e adott meg negatív értéket, és lekezelni.

2024-11-06 19:36 UTC, NagyIstvanGabor requested changes
Szia!

Az 5-ös házid már szuper, viszont továbbra is jelen van a 4-es házid törlése a PR-ban.
A branch amiről nyitod a PR-t egy üres file-t tartalmaz a 4_exceptions_logging/to_do.py-hoz:

https://github.com/Global-rd/python_hu/blob/feherbarnabas/homework_5/homeworks/feherbarnabas/4_exceptions_logging/to_do.py.

Vagy másold ide vissza a file tartalmát, vagy menj át a main-re, fetch, pull, és hozz létre ott egy új 5-ös branch-et (előtte másold ki valahova az 5_oop mappát). Másold be ide az 5-ös házit és nyisd újra a PR-t.
![image](https://github.com/user-attachments/assets/f01c69a9-52d1-48c6-90f7-14c570f45591)

Ha ezen a tabon csak 1 files changed van, az 5-ös házi, akkor jók vagyunk. Köszi!

2024-11-07 08:34 UTC, barnaf03 commented
![Képernyőkép 2024-11-07 093328](https://github.com/user-attachments/assets/c869de98-ecd7-4ff0-8f05-28737070fc62)
 Ezt írja ki, hogyha publishelni szeretném az új branchet.

2024-11-08 17:54 UTC, NagyIstvanGabor commented
> ![Képernyőkép 2024-11-07 093328](https://private-user-images.githubusercontent.com/182502664/383877189-c869de98-ecd7-4ff0-8f05-28737070fc62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwODg2NTIsIm5iZiI6MTczMTA4ODM1MiwicGF0aCI6Ii8xODI1MDI2NjQvMzgzODc3MTg5LWM4NjlkZTk4LWVjZDctNGZmMC04ZjA1LTI4NzM3MDcwZmM2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxNzUyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmY5MWQ3MTQyYWFhYzRmNDMyMGIwNDAyMmFlYTUxZDg5MGYxMjVmNTI0MmViZGQwOTI4YzFmMWJhMDg2ZGI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.G4HnPvf50i-EwbT8Oq4jqpkoyYnWKYedB8ntVaFiSMY) Ezt írja ki, hogyha publishelni szeretném az új branchet.

Szia!

Valószínűleg azért, mert törölted local-ból az 5-ös branchedet, de remote-ról nem. Ezután létrehoztad ugyanazzal a névvel, és így létezik egy másik verzió remote-on. Zárd ezt a PR-t és akkor feldobja hogy törölni akarod e a branch-et is. Töröld, és utána menni fog.

2024-11-08 17:55 UTC, closed without merging