egetoimre/homework-5
Global-rd/python_hu pull request #177
Opened 2024-11-05 10:01 UTC by EgetoImre

5. házi feladat

2024-11-05 10:52 UTC, NagyIstvanGabor requested changes
Szia!

Nagyon szuperül használod az OOP alapjait. Pár apróságot jeleztem csak kommentben, kérlek nézd át őket és javíts ahol szükséges. Ha ezek megvannak approve-olom is. Köszi szépen!

2024-11-05 10:52 UTC, NagyIstvanGabor commented on homeworks/egetoimre/5_oop/car_fleet_mgr.py
> +    def drive(self, distance):
Szuper lenne, ha a `drive() `és a `refuel()` megvizsgálná, hogy nem e negatív az input.

2024-11-05 10:52 UTC, NagyIstvanGabor commented on homeworks/egetoimre/5_oop/car_fleet_mgr.py
> +        self.cars.remove(car)
itt meg kéne vizsgálni törlés előtt hogy az adott autó tényleg benne van e a flottában:
`if car not in self.cars:` különben ValueError-t kapunk egy nem létező objektum törlésénél.

2024-11-06 06:58 UTC, EgetoImre commented
Köszönöm szépen az észrevételeket. Javítottam a kódot.

2024-11-06 19:37 UTC, NagyIstvanGabor approved these changes
Szuper, köszönöm szépen! Approve-oltam, mehet a merge.

2024-11-10 17:35 UTC, merged