Zsoltcsengeri/homework 5
Global-rd/python_hu pull request #178
Opened 2024-11-05 15:24 UTC by zsoltcsengeri

Szia István,

Sajnos csak az első résszel vagyok készen, ennek elkészítése is nagyon sok időt vett igénybe. Remélem, lesz még 48 órám, hogy esetleg hozzáadhassam a második részt is?

Köszönöm, 
Zsolt

2024-11-05 15:36 UTC, NagyIstvanGabor requested changes
Szia!

Természetesen, sőt, a 48 óra az igazából a szerdai határidő utáni első általam adott visszajelzéstől számít, szóval ha egyből tudok rá reagálni, akkor is ráérsz még péntekig.
Egyébként nagyon szuper az első rész, ügyesen a használod a tanultakat. Egy apróság a `refuel()` és a `drive() ` method-hoz: ellenőrizd kérlek hogy a felhasználó nem adott e meg negatív számot. Ezen kívül minden szuper, várom a második részt, köszi szépen!

2024-11-06 19:39 UTC, NagyIstvanGabor commented
> Szia, Feltöltöttem a negatív számok kezelését a refuel és drive metódusokban. Köszönöm!

Szia! Köszi, az első rész így tökéletes.

2024-11-09 11:34 UTC, zsoltcsengeri commented
Szia István! 

Felpusholtam a második részt is. 
Kérlek, ellenőrizd, ha lesz időd. 
Nagyon köszönöm az instrukciókat és a visszajelzést!

Zsolt

2024-11-09 12:00 UTC, NagyIstvanGabor requested changes
Szia!

Köszi szépen a második részt! Jól használod a compositiont a Fleet-ben.
Két apróságot jeleztem kommentben, ezeket javítsd kérlek és approve-olom is. Köszi szépen.

2024-11-09 12:00 UTC, NagyIstvanGabor commented on homeworks/zsoltcsengeri/5_oop/car_fleet_mgr.py
> +    def remove_car(self, brand: str) -> None:
Ha csak a brand alapján törölsz, akkor ha pl több Ford típusú autó van a flottában, minden törlődni fog.
Szuper lenne ha magát az object-et törölnéd amit átadsz:

```
def remove_car(self, car:Car):
    if car in self.cars:
        self.cars.remove(car)
```

Így a kód is egyszerűbb, és az objektum memory address-e alapján töröl, ami egy egyedi azonosító.

2024-11-09 12:00 UTC, NagyIstvanGabor commented on homeworks/zsoltcsengeri/5_oop/car_fleet_mgr.py
> +        print("Total mileage of all cars in the fleet:", fleet1.cumulative_miles())
A return után a method végrehajtás véget ér, és kilépünk oda ahonnan a metódus meg lett hívva, így ez a print nem fog már lefutni. Nyugodtan töröld.

2024-11-09 15:14 UTC, zsoltcsengeri commented on homeworks/zsoltcsengeri/5_oop/car_fleet_mgr.py
> +        print("Total mileage of all cars in the fleet:", fleet1.cumulative_miles())
Szia István!

Köszönöm a javaslatokat, implementáltam őket. Kérlek, nézd meg, ha lesz időd. Nagyon köszönöm a segítséget és az iránymutatást!

Üdv,
Zsolt

2024-11-09 16:33 UTC, NagyIstvanGabor approved these changes
Szia, így már szuper minden, köszi szépen a gyors változtatásokat. Approve-oltam is, mehet a merge.

2024-11-11 18:31 UTC, merged