Franktoth - homework 41
Global-rd/python_hu pull request #181
Opened 2024-11-05 18:01 UTC by stFrank79

Jaj de bírnám, ha ez így már jó lenne :)

Üdv:
Frank

2024-11-05 22:51 UTC, NagyIstvanGabor requested changes
Most ez a helyzet: 
![image](https://github.com/user-attachments/assets/92e4892f-f9fb-469d-abc0-1ec535fe3d60)

Valahogy létrehoztál egy 3_conditional_loops mappát a conditional**s**_loops mappa helyett, vagy átnevezted :) 
Ha hozzáteszed azt az s betűt a mappához ami valahogy eltűnt, jók kéne legyünk :)
Most az van, hogy ezt a mappát az s betű nélkül újként érzékeli, és mivel így nincs meg az a mappa ami a main-en s betűvel ott van, ezért azt törölné.
Egyébként itt tudod ellenőrizni hogy minden oké e:
![image](https://github.com/user-attachments/assets/f342b38a-e177-4127-b105-708ffcb3ed4d)

Ha itt 1 file changed van, ami a to_do.py a 4_exceptions_logging-ban, akkor megvagyunk.  Az 5-ös házinál is az lesz a gond hogy egy olyan branch alapján hoztad létre, amiben a 3-as mappa nem létezik.

Holnap napközben küldök egy screenshare-es videót Discord-on, ami alapján szerintem könnyebb lesz megcsinálni.

2024-11-06 10:34 UTC, stFrank79 commented
Szia!

Köszi a videókat. Válaszoltam a Discordon.
Most kijavítottam a könyvtár nevét, ha így engeded a merge-et, nem rakja rendbe a main-ben lévő franktoth könyvtárakat is a 4-esig bezáróan?

Üdv:
Frank

2024-11-06 19:41 UTC, NagyIstvanGabor reviewed
Szia! Ezt a PR-t elengedhetjük, zárd kérlek. Köszi!

2024-11-06 21:49 UTC, stFrank79 commented
Ohlala, good point!

Törölve!

2024-11-06 21:49 UTC, closed without merging