_HW_5_1st variant
Global-rd/python_hu pull request #190
Opened 2024-11-06 08:47 UTC by JanosV2

Ready to publich after commit

2024-11-07 09:16 UTC, NagyIstvanGabor requested changes
Szia!

A házidban jól használod az OOP órán tanultakat, néhány apró hibára hívtam fel a figyelmet kommentekben, ezeket kérlek javítsd, utána megy is az approve. Köszi szépen!

2024-11-07 09:16 UTC, NagyIstvanGabor commented on homeworks/vulmanjanos/5_oop/car_fleet_mgr.py
> +    def drive(self, driven_kilometers):
szuper lenne megvizsgálni, hogy a driven_kilometers nem e negatív szám, különben csökkented a mileage-ot és növeled a fuel level-t.

2024-11-07 09:16 UTC, NagyIstvanGabor commented on homeworks/vulmanjanos/5_oop/car_fleet_mgr.py
> +    def refuel(self, refill):
hasonlóképp itt is érdemes megvizsgálni hogy nem e 0 vagy negatív szám a refill

2024-11-07 09:16 UTC, NagyIstvanGabor commented on homeworks/vulmanjanos/5_oop/car_fleet_mgr.py
> +    def remove_car(self, car):
meg kéne vizsgálni törlés előtt hogy a car object benne van e a self.skodacars-ban, különben ValueError-t kapsz.

2024-11-09 08:35 UTC, JanosV2 commented
Köszi a kommenteket és javaslatokat. Mindhárom pontban néhány sorban hozzáadtam a szükséges módositásokat. 
Köszi.

2024-11-09 10:32 UTC, NagyIstvanGabor requested changes
Szia!

Köszi a módosításokat. Ez még így nem teljesen jó mert most kétszer van definiálva a drive() és a refuel(). 
Mindkét esetben a második implementációval felülírod az elsőt, és így soha nem csekkolja a negatív értékeket amikor meghívjuk.
Ez a negatív érték vizsgálat szimplán legyen kérlek része az eredeti metódusoknak. Pl:

```
    def drive(self, driven_kilometers):
        if driven_kilometers < 0:
            print("Driven kilometers cannot be negative.")
            return
        fuel_consumption_calculator = driven_kilometers * 0.1
        if fuel_consumption_calculator <= self.fuel_level:
            self.mileage += driven_kilometers
            self.fuel_level -= driven_kilometers
        else:
            print("Not sufficient fuel amount to drive the desired distance.")
```

ugyanez a logika a refuel-nél is. Köszi!

2024-11-09 11:23 UTC, NagyIstvanGabor approved these changes
Így már szuper, köszi!
Approve-oltam, mehet a merge.

2024-11-09 11:24 UTC, merged