dobrikbartaeva/homeworks 4
Global-rd/python_hu pull request #191
Opened 2024-11-06 10:07 UTC by evadobrik

2024-11-07 09:45 UTC, NagyIstvanGabor requested changes
Szia!

Ez a PR tartalmazza az 5-ös házidat is, azt kérlek töröld erről a branch-ről, és push-old a változtatást a PR-ba.

A 4-eshez írtam néhány javítandó dolgot kommentben, azokat nézd át kérlek.
Az 5-öst a saját PR-jában értékelem ,köszi szépen!

2024-11-07 09:45 UTC, NagyIstvanGabor commented on homeworks/dobrikbartaeva/4_exceptions_logging/to_do.py
> +        print(f"You added: {task_input}")
printek helyett célszerűbb lenne a logger-t használni amit a 28. soron létrehoztál

2024-11-07 09:45 UTC, NagyIstvanGabor commented on homeworks/dobrikbartaeva/4_exceptions_logging/to_do.py
> +def remove_task(task_input):
Ez a function egy kicsit lehetne effektívebb, mert így egyesével írod vissza a file-ba a feladatokat, és ahogy nő a file mérete ez egyre több időbe fog telni:

```
def remove_task(task_input):
    with open(to_do_list_path, "r") as file:
        lines = file.readlines()

    new_lines = [line for line in lines if line.strip() != task_input]
    if len(new_lines) == len(lines):
        print(f"This task is not on your to do list: {task_input}")
    else:
        with open(to_do_list_path, "w") as file:
            file.writelines(new_lines)
        print(f"You removed: {task_input}")
```

Itt egy lehetséges megoldás, beolvasod az összes sort egy listába, majd egy list comprehension-nel megtartod azokat a sorokat amik nem tartalmazzák a megadott taskot (akár többször is ugyanazt).
Ezután csak visszaírod az egész listát úgy ahogy van, egyszerre.

2024-11-07 09:45 UTC, NagyIstvanGabor commented on homeworks/dobrikbartaeva/4_exceptions_logging/to_do.py
> +def exit_file():
ha ez simán csak False-t return-öl, nem kell a global. Lent a while-ban kell hogy ezt a False-t megkapd.

```
def exit_file():
    print("Exiting...")
    return False
```

2024-11-07 09:45 UTC, NagyIstvanGabor commented on homeworks/dobrikbartaeva/4_exceptions_logging/to_do.py
> +        action_list[action_number][-1](task_input)
itt `running_code = action_list[action_number][-1](task_input)`
legyen, és akkor False esetén kilép

2024-11-07 09:45 UTC, NagyIstvanGabor commented on homeworks/dobrikbartaeva/4_exceptions_logging/to_do.py
> +        action_list[action_number][-1]()
itt is `running_code = action_list[action_number][-1]()`

2024-11-08 18:44 UTC, NagyIstvanGabor submitted a review, later dismissed
Szia!

Nekem nem dobott hibát a logger.info-kra, szóval úgy néz ki sikerült megoldani. Ha valami kérdésed van még ezzel kapcsolatban akkor jelezd kérlek. 
Approve-oltam, köszi szépen mehet a merge.

2024-11-09 07:21 UTC, evadobrik commented
<img width="641" alt="image" src="https://github.com/user-attachments/assets/b557321c-633b-4cc7-b93b-331a70184890">

Nekem kilép a programból és nem kérdezi meg újra hogy most mit szeretnék.

2024-11-09 09:52 UTC, NagyIstvanGabor commented
> <img alt="image" width="641" src="https://private-user-images.githubusercontent.com/182787314/384585639-b557321c-633b-4cc7-b93b-331a70184890.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNDUzNjMsIm5iZiI6MTczMTE0NTA2MywicGF0aCI6Ii8xODI3ODczMTQvMzg0NTg1NjM5LWI1NTczMjFjLTYzM2ItNGNjNy1iOTNiLTMzMWE3MDE4NDg5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwOTM3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOGZkYTNkMDZmZjIyNDhmYmYzNGJmZDEyMzA0YzljNzVkMTE5OWQzN2NkMTdiYTRlMGRkMTcwNGY1ZWM2NTU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OaOAg_GYkkeY2eVPnxu73lryNswhCvBO4gtCZlTj6cs">
> Nekem kilép a programból és nem kérdezi meg újra hogy most mit szeretnék.

Áh értelek, a gond ott van hogy a `view_task()`, az` add_task() `és a `remove_task()` mind None-t return-öl (mert hogy nem adtad meg direktben hogy mit return-öljenek, nincs konkrét return statement egyikben sem). Printeld ki a running_code-ot a while loop végén és látni fogod.
Amikor ezt vizsgálod:

`while running_code:`

Ezt azt nézi hogy a `running_code` változó True e. Az első iterációt leszámítva soha nem lesz True, mert az add, view, remove metódusok None-t return-ölnek, az exit pedig False-t. Ezt elfelejtettem hozzátenni az előző komentemhez, ne haragudj:
Ahhoz hogy ez működjön, az add, remove és view metódusok végére kell egy return True. Ez egy visszajelzés a while loop-nak hogy minden rendben ment a function futtatásakor, és továbbra is folytatni akarod.

Közben látom hogy merge conflict-od van, nem pontosan értem hogy hogyan mert semmit nem változtatsz a mostani PR-ban ami  már bent van a main-ben. A legegyszerűbb megoldás ha miután ezeket a return True-kat hozzáadtad a function-ök végére, kimásolod a 4-es mappát valami független helyre, pl az asztalodra.
Törlöd ezt a branch-et localból és remote-ról is (amikor github desktopban törlöd, megkérdezi remote-on is akarod e).
Menj át a main-re, fetch, pull, hozz létre egy új 4-es házi branch-et, másold be a házidat és nyiss egy új PR-t. Ezután approve-olom is.
Valami itt összeakadt amiatt hogy a 4-es és 5-ös házi is itt volt, közben az 5-ös már be lett merge-ölve, és így egyszerűbb megoldani. Köszi!

2024-11-09 12:00 UTC, evadobrik commented
Nem engedi törölni... 

<img width="799" alt="image" src="https://github.com/user-attachments/assets/76d1fb74-9179-4e00-91db-1e488f49c790">

![image](https://github.com/user-attachments/assets/a4ce7b34-8b65-46fa-ae3f-03637a18029b)

![image](https://github.com/user-attachments/assets/a965f045-b440-4288-983e-027143515265)

2024-11-09 12:01 UTC, closed without merging