5th homework
Global-rd/python_hu pull request #195
Opened 2024-11-06 15:32 UTC by DanTar93

2024-11-07 10:02 UTC, NagyIstvanGabor requested changes
Szia!

Van néhány apróság ami javításra szorul, de a házi nagy része rendben van, inkább apró logikai hibákról van szó. Ezeket javítsd kérlek és approve-olom is. Köszi szépen!

2024-11-07 10:02 UTC, NagyIstvanGabor commented on homeworks/taridaniel/5_oop/car_fleet_mgr.py
> +class Fleet(Car):
a Fleet nem kell hogy örököljön a Car-tól. A flottának nincs üzemanyagszintje, nincs óraállása, nincs gyártási éve stb. és nincs szüksége sem a drive sem a refuel metódusokra.

2024-11-09 09:25 UTC, DanTar93 commented
Szia István!
Nem tudom, hogy átment-e az újabb verzió a kért változtatásokkal. A GitHub Desktop sokat "homokórázott", majd azt írta ki, hogy a commitolás és pusholás sikeres volt, de egyből magától be is záródott a program. Így még nem viselkedett, ezért gondoltam megkérdezlek, hogy látod-e a változtatott verzióját a házimnak.

2024-11-09 10:23 UTC, NagyIstvanGabor approved these changes
Szia!

Igen látom a változtatásokat, köszi szépen. Approve-oltam is, mehet a merge.
Azért történt ez amit leírtál mert a branch-ről amin vagy, meg volt már nyitva ez a PR.
Ha commit-olsz és push-olsz, akkor automatikusan frissíted a PR-t.

2024-11-09 11:14 UTC, merged