Nemethmate homework 5
Global-rd/python_hu pull request #198
Opened 2024-11-07 17:30 UTC by Methmat

2024-11-07 18:09 UTC, NagyIstvanGabor requested changes
Szia!

Az 5-ös házid szuper, 1 dolgot kértem csak be mint változtatás.
A PR-od tartalmazza a 4-es házit is, ezt innen töröld kérlek. Köszi!

2024-11-07 18:09 UTC, NagyIstvanGabor commented on homeworks/nemethmate/5_oop/car_fleet_mgr.py
> +    def drive(self, kilometers):
ellenőrizd kérlek, hogy a kilometers paraméter nem e negatív szám. Ha az akkor igazából visszatekered az óraállást és megtankolod az autót a drive metódussal.

2024-11-07 19:38 UTC, Methmat commented on homeworks/nemethmate/5_oop/car_fleet_mgr.py
> +    def drive(self, kilometers):
Köszi. Elvben javítottam és töröltem a 4-es leckét

2024-11-08 18:08 UTC, NagyIstvanGabor approved these changes
Szia!

Szuper köszi szépen. Approve-oltam is, mehet a merge.

2024-11-09 11:30 UTC, merged