gaalistvantamas/homework-5
Global-rd/python_hu pull request #199
Opened 2024-11-07 22:53 UTC by GaalIstvanTamas

2024-11-08 18:06 UTC, NagyIstvanGabor requested changes
Szia!

Szuperül használod az OOP órákon tanultakat, néhány apróságot kértem csak be mint változtatás. Kommentekben jeleztem ezeket. Köszi szépen!

2024-11-08 18:06 UTC, NagyIstvanGabor commented on homeworks/gaalistvantamas/5_oop/car_fleet_mgr.py
> +        if refuel_percents < 1:
Itt a hibaüzenet és a feltétel nincs összhangban. Ha megadom hogy tankoljon 0.5%-nyit, hibát kapok hogy 0-nál nagyobb számot adhatok csak meg. Vagy az legyen hogy refuel_percents `<= 0`
vagy a hibaüzenet legyen az hogy `"The minimum amount for refueling is 1 %"` vagy valami hasonló.

2024-11-08 18:06 UTC, NagyIstvanGabor commented on homeworks/gaalistvantamas/5_oop/car_fleet_mgr.py
> +        if road_length_in_kilometres < 1:
ugyanaz a gond mint a refuel-nél, ott leírtam a részleteket, hozd kérlek összhangba a feltételt és a hibaüzenetet.

2024-11-08 18:06 UTC, NagyIstvanGabor commented on homeworks/gaalistvantamas/5_oop/car_fleet_mgr.py
> +        self.cars.remove(car_to_be_removed)
itt szuper lenne megvizsgálni, hogy benne van e a car_to_be_removed a self.cars-ban. Ha nincs, és megpróbáljuk remove-olni, akkor ValueError Exception keletkezik.
simán nézd meg így:
```
if car_to_be_removed in self.cars:
   self.cars.remove(car_to_be_removed)
```

2024-11-08 18:06 UTC, NagyIstvanGabor commented on homeworks/gaalistvantamas/5_oop/car_fleet_mgr.py
> +        else:
ebben az esetben menjen kérlek annyit az autó amennyire elegendő üzemanyag a rendelkezésére áll (ennek függvényében változzon a mileage és a fuel level)

2024-11-08 22:38 UTC, GaalIstvanTamas commented
Szia! Elkészítettem a változtatásokat és drive-hoz tettem egy feltételt, hogy csak akkor engedjen vezetni, ha van üzemanyag az autóban. :)

2024-11-09 10:17 UTC, NagyIstvanGabor approved these changes
Szia!

Szuper köszi szépen! Approve-oltam, mehet a merge.

2024-11-09 10:47 UTC, merged