Dankkhazipeter/homework 6
Global-rd/python_hu pull request #205
Opened 2024-11-09 19:47 UTC by roniekoma

Az alapfeladat megoldását tettem az első commitba

Az osztály fejlesztését a másodikba

És az új funkciók tesztelését a harmadik commitba

2024-11-12 08:31 UTC, NagyIstvanGabor approved these changes
Szia!

Ezt nagyon alaposan körbejártad, a coverage is 100%. Nagyon szép munka!
Approve-oltam, mehet is a merge.

2024-11-12 08:36 UTC, NagyIstvanGabor requested changes
Szia!

Ne haragudj, minden áll amit felül írtam, de most szúrtam ki hogy ebben a mappádban van egy requirements.txt is.
Ezt innen töröld kérlek, ez minden esetben a project root-jában van: https://github.com/Global-rd/python_hu/blob/main/requirements.txt
Itt már itt van a pytest és minden depdency-je. Amennyiben használsz valamit olyan dependency-t ami teljesen új, azt is ebbe a root-ban lévő requirements.txt-be írd kérlek (pip freeze > requirements.txt ha a root a current working directory-d). Köszi szépen.

2024-11-13 19:23 UTC, roniekoma commented
> Szia!
> 
> Ne haragudj, minden áll amit felül írtam, de most szúrtam ki hogy ebben a mappádban van egy requirements.txt is. Ezt innen töröld kérlek, ez minden esetben a project root-jában van: https://github.com/Global-rd/python_hu/blob/main/requirements.txt Itt már itt van a pytest és minden depdency-je. Amennyiben használsz valamit olyan dependency-t ami teljesen új, azt is ebbe a root-ban lévő requirements.txt-be írd kérlek (pip freeze > requirements.txt ha a root a current working directory-d). Köszi szépen.

Szia! Bocs, hogy csak most tudok válaszolni. Direkt tettem a saját mappámba, mivel azt gondoltam, hogy a mi speciális esetünkben nem kellene projektként kezelni ezt az egész repot, hiszen mindenkinek más a házija és igaziból minden házi is (mappa) független egymástól. Ezért én magamnál az env-et kizárólag erre a mappára hoztam létre és készítettem el a requirements.txt fájlt.

Hogy ha valami újat használok és a külső mappában található requirements.txt-be küldöm be változtatásba azt is, akkor az approve és merge után mindenkihez bekerül, ami szerintem indokolatlan.

Ezen kívül még annyi, hogy azért tettem be külön, mert amikor a megoldásomat beküldtem, akkor a külső requirements.txt fájlban még nem volt ott a pytest :)

Ezt 9-én, este 10-kor küldted be: https://github.com/Global-rd/python_hu/blob/884f528850d3ff29fd3bec5b48568a76d9c2c36e/requirements.txt

Én pedig 9-én, 8:47-kor küldtem be este a megoldásom, kb. 1 órával előtte :D  

Ettől még kivettem, természetesen egyáltalán nem ragaszkodom hozzá, hogy ott legyen ilyen fájlom, csak szépen akartam csinálni :)

2024-11-13 19:25 UTC, roniekoma commented
Kivettem a sajátomat, rebase-eltem a main-re és force pusholtam, hogy minden rendben legyen :D

2024-11-13 22:38 UTC, NagyIstvanGabor approved these changes
Szia!

Köszi, hogy kivetted. Megértem az érvelésed a külön requirements.txt-hez csak a saját mappádba, de nem szerettem volna ha ez rögzül bárkinél, hogy subfolderekben tartogatunk requirements.txt-ket, ezért döntöttem a szokásos project-level requirements.txt approach mellett.
Valóban hamarabb küldted be a pytest hozzáadását a requirements.txt-vel, ezzel semmi gond, most is approve-oltam a 7-es házidnál, az volt a gond hogy a saját folderedben volt.
Attól, hogy a requirements.txt-be bekerül egy dependency amivel csak te dolgozol, másnak még nem kötelező azt feltelepíteni, ha nem akar futtatni semmit a te mappáidból. Azonban azt is fontosnak tartom, hogy adott esetben egymástól is tanuljatok, ránézzetek egymás megoldásaira/futtassátok egymás kódját, és ilyenkor egy pip install -r requirements.txt-vel fel  tudtok rakni mindent, nem az errorokat követve kell egyesével telepítgetni a dependency-ket.

Köszi szépen hogy a 7-esnél már a root-ban lévő .txt-be írtad a pandas-t!
Approve-oltam ezt is, mehet a merge.

2024-11-14 21:09 UTC, merged