feherbarnabas/homework_6
Global-rd/python_hu pull request #214
Opened 2024-11-11 16:22 UTC by barnaf03

2024-11-12 10:28 UTC, NagyIstvanGabor requested changes
Szia!

Próbáld meg kérlek lefuttatni a teszteket. A pytest parancs azért nem működik mert "testing_"-nek hívod a file-t "test_" helyett. 
Nevezd át test_bankaccount.py-ra és elő fog jönni egy csomó szintaktikai hiba, ezeket kérlek javítsd, és utána ellenőrizd a tesztek eredményét. Köszi szépen.

2024-11-12 12:18 UTC, barnaf03 commented
Szia! Átnéztem a kódot, és sok elütés vagy félreértelmezést találtam. Megpróbáltam kijavítani őket.

2024-11-14 09:44 UTC, NagyIstvanGabor requested changes
Szia!

Próbáld lefuttatni a pytest parancsot, maradt még sajnos benne hiba:

`ERROR homeworks/feherbarnabas/6_testing/test_bankaccount.py - Failed: In test_withdraw_valid: function uses no argument 'amount'`
Jelezd nyugodtan ha segítségre van szükséged a tesztekkel.
Köszi szépen.

2024-11-14 18:03 UTC, NagyIstvanGabor approved these changes
Szuper köszi szépen! Approve-oltam is, mehet a merge.

2024-11-14 18:05 UTC, merged