becseipeter/homework_6
Global-rd/python_hu pull request #219
Opened 2024-11-12 20:28 UTC by BecseiPeter

2024-11-14 16:09 UTC, BecseiPeter commented on homeworks/becseipeter/6_testing/homework_06_helper/test_bank_account.py
> +def empty_bank_account():
Szia! nem igazán értem hol látod az ERROR-t...nálam nem dobott semmit. Kiszedtem az empty_bank_account-os sort, remélem így már jó lesz. :)

2024-11-14 17:57 UTC, NagyIstvanGabor commented on homeworks/becseipeter/6_testing/homework_06_helper/test_bank_account.py
> +def empty_bank_account():
Szia!

Futtasd le ezt kérlek a terminálodban (legyen a current working directory a project root-ja):

pytest homeworks/becseipeter/6_testing/homework_06_helper/test_bank_account.py

így csak a saját test_file-odat fogja futtatni és látni fogod a hibákat.

2024-11-14 17:58 UTC, NagyIstvanGabor requested changes
Szia!

Hagytam egy kommentet arról hogy hogy tudod megjeleníteni a hibákat. 
A mappa struktúrádat is javítsd kérlek, a homework_06_helper mappa nem kell a 6_testing-en belülre. Köszi.

2024-11-14 19:07 UTC, BecseiPeter commented
Szia István! Megoldottam a problémákat és olyan kérdésem lenne ami már a 7. leckével kapcsolatos. Próbáltam/om letölteni a CSV fájlt a weboldalról, de sehol sem látom/találom..... ezt hogy kell? :D Ha ez a feladat is a házi része akkor valahogy megoldom, de ha nem akkor hogy kell leszedni a saját gépemre ezt a fájt? Ennek mi a menete? Mert az oké, hogy megnyitom az oldalt meg jobb oldalon látom a request-eket alatta meg maga a kódot, de sehogy nem tudom beolvastatni....Bal oldalon a fülek között ott a Coins mappa és ha rányomok akkor nagyon sok almapap jelenik meg. Nem melyik kell ezek közül? Köszi a segítséget. :)

2024-11-16 09:14 UTC, NagyIstvanGabor requested changes
Szia!

Szuper, hogy megoldottad a problémákat, de push-old is légyszi a változtatásokat, mert itt még az előző problémás verzió van.

A 7-es háziban nem használunk csv file-okat, a feladatban egy api szerepel, aminek a markets endpointjáról kell adatokat lehúznod a requests library segítségével. 
Ezt tanultuk a 13. órán. Az adatok json formátumban érkeznek, ezeket kell átalakítanod pandas dataframe-mé és így megoldani a feladatokat.

2024-11-16 10:41 UTC, NagyIstvanGabor approved these changes
Köszi, ezt approve-oltam is. Ha a 7-essel kapcsolatban szükséged van segítségre, nyiss kérlek egy külön PR-t rá, és folytassuk ott. Köszi!

2024-11-16 10:42 UTC, merged