1-es hazi feladat
Global-rd/python_hu pull request #22
Opened 2024-09-24 19:38 UTC by slaca069

ez itt a leiras :)

2024-09-24 20:43 UTC, NagyIstvanGabor requested changes
Szia!
Írd át kérlek a pull request címét (itt githubon meg tudod tenni ha az Edit-re kattintasz a pull request címe mellett) úgy, hogy már a címből azonosítható legyél. Pl: simonlaszlo/1-es hazi feladat. 
A kommentekben ìrt tìpusok helyesek, viszont minden esetben egy string-et printelsz ki.
Ha quote-ok közè raksz valamit, az onnantòl kezdve egy string lesz.
A "" nem egyenlő a None-nal, az egy üres string, mìg a None az informàciò teljes hiànya. Erről beszèlünk majd mèg az òràn rèszletesen. Ha ezeket javítod, kèsz is vagy.
Köszi!

2024-09-25 14:38 UTC, NagyIstvanGabor reviewed
Szia!

A main.py-ban a változtatások szuperek, már csak a PR nevét írd át légyszi úgy, ahogy az előző kommentben írtam (a lényeg h a neved benne legyen valahogy, hogy azonosítható legyél már a PR listában is). Ha ez megvan, megy az approve. Köszi!

2024-09-25 14:44 UTC, slaca069 commented
Upsz, telefonon olvastam, az valahogy lemaradt. :)

2024-09-25 14:56 UTC, slaca069 commented
Végre megtaláltam..

2024-09-25 15:13 UTC, NagyIstvanGabor approved these changes
Szuper, köszi! Max pont, mehet a merge!

2024-09-25 15:14 UTC, merged