Valitothattila/homework 06
Global-rd/python_hu pull request #222
Opened 2024-11-13 01:00 UTC by vali-toth-attila

2024-11-14 10:07 UTC, NagyIstvanGabor requested changes
Szia!

A tesztjeid jók, de nem szükséges ennyi különböző fixture-t létrehozni. 
A fixture-ök értékeit nem változtatják a tesztjeid, szóval a legutolsó tesztben is a fixture objektum eredeti állapota lesz átadva a tesztnek. Így igazából ha létrehozol 2 fixture-t az elején (pl bankaccount1 és bankaccount2), ezzel a kettővel mindent meg tudsz csinálni.

Ebben a PR-ban valamiért törölted az órai anyagok közül a test_shopping_cart-ot, ezt javítsd kérlek:
![image](https://github.com/user-attachments/assets/f06ff70b-191e-47e2-940c-c08e780ccb5c)
Köszi szépen.

2024-11-16 10:05 UTC, NagyIstvanGabor requested changes
Szia!

Látom hogy hozzátettél a .gitignore-hoz dolgokat, köztük a lessons-ös file-okat is, ezeket töröld innen kérlek. Az órai anyagokat nem szeretnék kizárni a verziókövetésből.
A probléma az, hogy töröltél a saját branch-eden egy file-t, ami létezik a main branch-en. Ezért a PR-odban ezt a github úgy érzékeli, hogy te direkt törölted ezt a file-t, mert nem kell már a main-en. 
Mi tudjuk hogy nem ez a helyzet, szóval át kéne másolni a main-en lévő verziót a saját branch-edre.
Ehhez tedd a következőt kérlek:
Github desktop-ban menj a saját branched-re. Ezután menj a projekted mappájába, ezt kell látnod:
![image](https://github.com/user-attachments/assets/fe40248f-8d8f-4e8d-9daa-163512907232)
itt jobb klikk valahova az üres területre -> Open Git Bash here. Ez meg fog nyitni egy command line-hoz hasonló git shellt.
Ide másold be a következőt:

`git checkout main -- lessons/12/test_shopping_cart.py`

Ezzel a main-ről áthúzod a törölt file-t a saját branch-edre és megoldódik a probléma. A ctrl+v nem működik itt, csak simán nyomj egy jobb klikket és Paste, aztán enter.
Köszi szépen!

2024-11-16 11:03 UTC, vali-toth-attila commented
Szervusz István, 
Megcsináltam amit kértél. Annyit szeretnék csak kérdezni, hogy ugyenezt kézzel megcsináltam korábbi biztonsági mentésekből az miért nem volt jó? Az eredmény ugyanaz lett. 
üdv.:
Attila

2024-11-16 12:27 UTC, NagyIstvanGabor requested changes
Szia!

Nem tudom pontosan hogy csináltad manuálisan, én az alapján írtam a visszajelzést amit a változtatott file-oknál látok, és ott a legutóbbi push után is törölve volt a test_shopping_cart.py.
Ami azt illeti még most is így van, mert nem push-oltad a változtatásokat:
![image](https://github.com/user-attachments/assets/a3f26c4e-6d75-424d-be25-cd512a691860)

2024-11-16 12:57 UTC, vali-toth-attila commented
Szervusz István,
Valamiért visszaáll mindig egy korábbi verzióra, ezért töröltem mindent a gépemről, git.ignor-t kipucoltam push-oltam, így egyet és utána megint törlődött a lesson12-ből a test fájl, visszaállítottam push-oltam megint. Szerintem most már jól néz ki minden! 
üdv.: Attila

2024-11-16 13:33 UTC, NagyIstvanGabor approved these changes
Szia!

Igen, így már minden rendben. Köszi szépen! 
Approve-oltam is, mehet a merge.

2024-11-16 13:34 UTC, merged