6 testing
Global-rd/python_hu pull request #237
Opened 2024-11-17 15:27 UTC by DanTar93

2024-11-17 15:39 UTC, NagyIstvanGabor requested changes
Szia!

szedd szét kérlek a teszteket egy külön file-ba, amit úgy nevezel el hogy "test_bankaccount.py". Itt a hangsúly azon van hogy "test_"-tel kezdődjön.
Best practice hogy a tesztelendő és a teszt file-ok külön vannak.
Hagytam még néhány apró javítani valót kommentekben, azokat nézd át légyszi. Köszi szépen!

2024-11-17 15:39 UTC, NagyIstvanGabor commented on homeworks/taridaniel/6_testing/bankaccount.py
> +def test_withdraw_invalid(account1):
Itt is érdemes lenne parametrize-t használni.

2024-11-17 15:39 UTC, NagyIstvanGabor commented on homeworks/taridaniel/6_testing/bankaccount.py
> +@pytest.mark.parametrize("amount", [0, -50])
szuper a parametrize, de a test_withdraw_invalidnál ahol több különböző dolgot tesztelsz egymás alatt lenne igazán hasznos.

2024-11-17 19:00 UTC, DanTar93 commented
Szia István!
Köszönöm a lehetőséget az újabb feltöltéshez és a javaslataidat is! Alakítottam a kódomon a leírásod alapján.

2024-11-18 10:01 UTC, nistvangabor requested changes
Szia!
Köszi a változtatásokat. Van még egy apró hiba a kódban:
a test file-ban bank_account-ot importolsz, de a file neve bankaccount.py underscore nélkül.
Így hibára fut a teszted. Javítsd kérlek és approve-olom is, köszi!

2024-11-18 15:01 UTC, DanTar93 commented
Köszönöm! Javítottam a hivatkozást.

2024-11-18 15:36 UTC, NagyIstvanGabor approved these changes
Köszi, approve-oltam is. Mehet a merge.

2024-11-18 16:12 UTC, DanTar93 commented
Köszi! Valamiért nem engedi a merge-ölést. Azt írja, hogy merging is blocked. Csak kommentelni tudok.

2024-11-18 16:27 UTC, nistvangabor approved these changes

2024-11-18 16:28 UTC, nistvangabor commented
> Köszi! Valamiért nem engedi a merge-ölést. Azt írja, hogy merging is blocked. Csak kommentelni tudok.

Szia!

Az én hibám volt, ne haragudj. Másik userrel voltam belogolva mint amiről eredetileg a változtatást kértem. Mostmár jó lesz. Köszi!

2024-11-18 16:29 UTC, merged