editerdelyhorvath-8
Global-rd/python_hu pull request #261
Opened 2024-11-24 14:37 UTC by NyugtonMalac

- weather_app.py fejlesztése - megmutatja a kívánt tartalmat a streamlit segítségével a weben
- weather_logs.db - a megadott módon létrehozott log file a futtatott kereséseket logolja
- db_connector.py - kezeli az adatbázis kapcsolatot és annak kezelését az órán tanultaknak megfelelően
- weather_app_functions.py : a felhasznált függvények külön file-ba rendezve az átláthatóság kedvéért
- check_logs.py - egyszerű logfile olvasás a terminálon

(Még nem deployoltam az app-ot a Community Cloud-ra. Deployment után a linket külön tervezem csatolni.)

2024-11-24 15:17 UTC, NyugtonMalac commented
Íme a link: 
https://weatherapppy-awbozk5jvagw6awynh4hqg.streamlit.app/

2024-11-28 08:10 UTC, NagyIstvanGabor requested changes
Szia!

A házid szuper, a két cache-elt function-nel kapcsolatban van csak egy észrevételem, ezt nézd át kérlek és javítsd. Ha megvan, approve-olom is. Köszi szépen!

2024-11-28 08:10 UTC, NagyIstvanGabor commented on homeworks/editerdelyhorvath/8_streamlit/weather_app_functions.py
> +@st.cache_data(ttl=600) # TTL (Time To Live) 10 min
ez és a get_forecast() function gyakorlatilag ugyanazt csinálja, csak az egyikben a weather endpoint-ra küldöd a request-et, a másikban a forecast-ra. Ez lehetne egy paraméter egy general function-ben, és akkor mindkettőt hibátlanul le tudnád kezelni. A cache is működne tovább, hiszen a cache a function és a megadott paraméterek kombinációjából jön létre (írtram ezzel kapcsolatban a technikai kérdések channelbe tegnap este)

2024-11-29 16:24 UTC, NagyIstvanGabor approved these changes
Szia!

Köszi szépen a változtatásokat, approve-oltam is, mehet a merge.
A kérdésedre a válasz:
A streamlit automatikusan updateli az app-ot, amikor push-olsz valamit a repoba amihez kötve van. Ha ez valamiért nem történik meg mégsem, akkor a jobb alsó sarokban kell legyen egy "Manage App" panel, ha rákattintasz akkor megjelenik 3 pötty. Ha erre is rákatitntasz lesz egy "Reboot" lehetőség. Ez meg kell oldja. Ha így sem megy valamiért, jelezd kérlek és belemászunk mégjobban. Köszi szépen!

2024-12-01 08:24 UTC, merged