Dankhazipeter/homework 8
Global-rd/python_hu pull request #263
Opened 2024-11-24 21:30 UTC by roniekoma

Streamlit link: https://weatherapp3.streamlit.app

Azt szerettem volna megoldani, hogy bal oldalon, a sidebaron a logs az egy gomb és modalban jeleníti meg a legutóbbi 10 logot. De ezt sajnos nem sikerült, bénáztam. Ha marad időm, akkor még beküldök egy új verziót.

2024-11-24 21:48 UTC, roniekoma commented
Na nem bírtam ki, megoldottam. Nem tökéletes, mert a modal megjelenésnél is lefut egy lekérés (cache-ből), de ezzel most már nem töltök időt, remélem nem gond. :)

2024-11-25 12:44 UTC, NagyIstvanGabor requested changes
Szia!

Tök jó a házid, viszont van néhány apróság amit javíts kérlek:

- nem adsz meg ttl-t a cache-ben, így gyakorlatilag amíg él a cache, Balatonszepezden és bármelyik lekért városban mindig ugyanolyan időt fogunk látni. Ez látszik a logokon is,  egy ideje 7.19 fok van Balatonszepezden :) 
- Ha megnézed a logjaid:

![image](https://github.com/user-attachments/assets/e108c6ab-18f7-4353-9dd8-55a927843759)

látod, hogy pontosan 5 percenként magától újrafut a teljes kód, (szerintem, ebben nem vagyok 100%-ig biztos, de ha nem oldja meg a javaslatom a problémát akkor utánanézek jobban) ez a streamlit live checkje miatt van. Ha beraknál egy gombot amit meg kell nyomni az adatok lekéréshez, megszűnne az auto logolás.

Köszi!

2024-11-26 19:22 UTC, roniekoma commented
> Szia!
> 
> Tök jó a házid, viszont van néhány apróság amit javíts kérlek:
> 
> * nem adsz meg ttl-t a cache-ben, így gyakorlatilag amíg él a cache, Balatonszepezden és bármelyik lekért városban mindig ugyanolyan időt fogunk látni. Ez látszik a logokon is,  egy ideje 7.19 fok van Balatonszepezden :)

Jajj, ez valóban egy elég komoly hiba, javítottam egy külön commitban.

> * Ha megnézed a logjaid:
> 
> ![image](https://private-user-images.githubusercontent.com/63602487/389526429-e108c6ab-18f7-4353-9dd8-55a927843759.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NDg4MzUsIm5iZiI6MTczMjY0ODUzNSwicGF0aCI6Ii82MzYwMjQ4Ny8zODk1MjY0MjktZTEwOGM2YWItMThmNy00MzUzLTlkZDgtNTVhOTI3ODQzNzU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDE5MTUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YWFlZDE5YWY2YmRhNGQ3NzYzMzU1ODk3OGE3ZWFhOTNhMzA2OGIyNWU0YmE0MmYzOTljYzRjNjc5OTZkY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4U4SBbHv1NuNaI-qyWmPyiFMvj0xW_AWO2roG3J1pAk)
> 
> látod, hogy pontosan 5 percenként magától újrafut a teljes kód, (szerintem, ebben nem vagyok 100%-ig biztos, de ha nem oldja meg a javaslatom a problémát akkor utánanézek jobban) ez a streamlit live checkje miatt van. Ha beraknál egy gombot amit meg kell nyomni az adatok lekéréshez, megszűnne az auto logolás.
> 
> Köszi!

Valami ilyesmi miatt lehet, de akkor ez minden olyan alkalmazással gond lesz, ahol van az inputban default value és betöltéskor betölt adatokat. (gondolom mindenkinek a megoldása ilyen). Megpróbálok rá megoldást hozni, írok még

2024-11-26 20:10 UTC, roniekoma commented
Úgy oldottam meg, hogy van egy főoldal és a másik két "oldal" csak a gombra kattintva tölt be. Nem tudom, így "hivatalos"-e ezt megoldani, lehet, hogy nem elegáns a változók állítgatása és ezeket nézni, hogy melyik oldalon vagyunk. Remélem ez így elfogadható.

2024-11-28 08:17 UTC, NagyIstvanGabor requested changes
Szia!

Teljesen jó ez a megoldás, köszi szépen! 
A cache-elést még add hozzá kérlek, és nézz rá a get_current_weather() és get_weather_forecast() function-ökre. Ugyanazt csinálja a kettő, csak eltérő endpoint-okkal. Ez (az endpoint mint string) lehetne egy paraméter egy general function-ben, ami lekezeli mindkettőt. A cache-elésnek nem fog gondot okozni, írtam erről a technikai kérdésekben tegnap este.

Köszi szépen!

2024-11-28 09:46 UTC, roniekoma commented
> Szia!
> 
> Teljesen jó ez a megoldás, köszi szépen! A cache-elést még add hozzá kérlek, és nézz rá a get_current_weather() és get_weather_forecast() function-ökre. Ugyanazt csinálja a kettő, csak eltérő endpoint-okkal. Ez (az endpoint mint string) lehetne egy paraméter egy general function-ben, ami lekezeli mindkettőt. A cache-elésnek nem fog gondot okozni, írtam erről a technikai kérdésekben tegnap este.
> 
> Köszi szépen!

Bocsánat, a nagy átszervezésben a cache-t véletlenül nem tettem be az újabb commitba :(

Csinálom és megnézem az összevonás lehetőségét is, bár bevallom őszintén, mivel teljesen mást csinál az üzleti logika szerint, nem biztos, hogy összevonnám egy get_weather_data függvénybe és paraméter lenne, hogy éppen melyik típus. Inkább valami "service"-be tenném ki a request feldolgozás részt, megnézem

2024-11-28 10:27 UTC, roniekoma commented
Na átalakítottam, ahogy szerintem értelmesebb, remélem Neked is tetszik. Cache is felkerült.

2024-11-28 10:35 UTC, NagyIstvanGabor approved these changes
Szia!

Én sem egy get_weather_data() function-re gondoltam, hanem egy tök általános get_data()-ra. A te megoldásod is szuper, nekem a lényeg az volt hogy a redundancy eltűnjön. Köszi a változtatásokat. Approve-oltam is.

2024-11-28 10:49 UTC, merged