kirkovvalentinivan\homework-8\weather_app
Global-rd/python_hu pull request #266
Opened 2024-11-25 21:38 UTC by vkirkov98

Szia István!

Elméletileg sikerült, kivéve a másik repóról való deployolás. 
Ez lenne a link:
https://rbdreamsweather.streamlit.app/
Bemásoltam a program kódot, a requirements.txt-t, a .streamlit-et, a .gitignore-t. Egyedül env-et nem csináltam és telepítettem a kódokat. A local-ról sikerült a közös repón futtatni.

Köszi,
Valentin

2024-11-28 08:32 UTC, NagyIstvanGabor requested changes
Szia!

Ahogy látom a deploy-olt appodból az api key-t hiányolja. Ezt hozzáadtad a streamlit-en belül?
Itt írtam erről részletesen Discod-on, remélem ez segít:
https://discord.com/channels/1278691503149158410/1278691503366996112/1311025766372475041

A mostani kódod szuper egyébként, egyedül annyit javíts kérlek hogy a fetch_current_weather és a fetch_forecast legyen egy function, mert szinte ugyanazt csinálják. Egyedül az endpoint tér el. A cache-nek ez nem fog ártani, erről itt írtam részletesen: 
https://discord.com/channels/1278691503149158410/1278691503366996112/1311456249920884868

Köszi szépen!

2024-11-28 21:04 UTC, vkirkov98 commented
Ha minden igaz, akkor most már sikerült deployolni is, mert én látom a weben és a kódot is remélem jól update-eltem. 

Köszi szépen a tanácsokat és a segítséget!

2024-11-29 17:10 UTC, NagyIstvanGabor requested changes
Szia!

Köszi szépen, alakul, de még van egy kis hiba. Egyrészről egy fokkal még lehetne egyszerűbb a function-öd:
A `data_type` paramétert csak arra használod hogy létrehozz ez alapján direktben egy másik változót. Megadhatnád direktben az endpoint-ot mint paraméter, és csak változóként berakhatnád az url f-stringjébe. Ez az ami most hiányzik mert az endpoint változót nem használod semmire, és mindig a weather adatokat hívod le:
![image](https://github.com/user-attachments/assets/02bd78c3-1b47-4b24-8331-815e98433f7b)
Itt látszik, hogy a map megjelenik, mert a weather endpoint működik, viszont mivel a forecast-hoz is a weather endpointot használod, ott nincs list key.

Ezt még javítsd kérlek és approve-olom. Köszi!

2024-12-01 11:53 UTC, nistvangabor approved these changes
Szia!

Igen, így már szuper, köszi!

2024-12-01 11:54 UTC, NagyIstvanGabor approved these changes

2024-12-01 12:10 UTC, merged