Frank Toth - Homework 8
Global-rd/python_hu pull request #267
Opened 2024-11-26 02:06 UTC by stFrank79

Szia!

Elkészült a 8-as házi első verziója, Kb úgy működik, ahogy az a leírásban szerepel, csak a térkép ráközelítés nem megy.
A Streamlit Community Cloudban is megtekinthető:
https://franktothweatherdashboard.streamlit.app/

Üdv:
Frank

2024-11-28 08:41 UTC, NagyIstvanGabor requested changes
Szia!

Szuper a házi, néhány apróság hiányzik csak:
- tegyél cache_data dekorátort a fetch_weather_data() function-re (ha  5 percenként frissül csak, bőven jó, de ez rád van bízva)
- szuper lenne ha lenne a keresődnek egy alapértelmezett értéke amikor megnyílik az oldal, pl Budapest. Akkor nem ez fogadná a felhasználót:

![image](https://github.com/user-attachments/assets/d0618993-de3d-45dd-9590-7b8697c8724b)
Az órai anyagban találsz erre megoldást, ott az egyik részvény ticker-t beraktuk alapértelmezettnek.

A map pedig csak erre a kiegészítésre szorul, és be fogja jelölni a térképen az adott várost:

```
    map_data = pd.DataFrame({
      "latitude": [lat],
      "longitude": [lon]
    })
    st.map(map_data)
```
Köszi szépen!

2024-11-29 12:12 UTC, stFrank79 commented
Szia!

Megcsináltam a változtatásokat. 
Köszi az útmutatót!

Üdv:
Frank

2024-11-29 17:12 UTC, NagyIstvanGabor approved these changes
Szuper, köszi szépen! Approve-oltam is, mehet a merge.

2024-11-30 17:11 UTC, stFrank79 commented
Köszi!

2024-11-30 17:11 UTC, merged