nagybalazs/homework-8
Global-rd/python_hu pull request #268
Opened 2024-11-26 09:04 UTC by balanagy23

[weather dashboard] - (https://weather-dashboard-ardbkhz8cpirxhmhrpectx.streamlit.app/)

2024-11-28 09:28 UTC, NagyIstvanGabor requested changes
Szia!

Szuper hogy beraktad a humidity forecast-ot is. Hagytam pár kommentet a kódhoz, ezeket javítsd kérlek. Köszi szépen!

2024-11-28 09:28 UTC, NagyIstvanGabor commented on homeworks/nagybalazs/8_streamlit/dashboard.py
> +@st.cache_data
adj meg ttl-t, hogy meddig éljen a cache, különben mindig ugyanazt az időt fogjuk visszakapni amíg nem resetelődik a szerver.

2024-11-28 09:28 UTC, NagyIstvanGabor commented on homeworks/nagybalazs/8_streamlit/dashboard.py
> +def get_current_weather(city: str) -> dict:
Ez, és a `get_weather_forecast()` szinte ugyanazt csinálja. Szuper lenne, ha egy function alá hoznád a kettőt, és paraméterként adnád meg hogy "weather" vagy "forecast" endpoint-ot használjon.

2024-11-29 17:35 UTC, NagyIstvanGabor submitted a review, later dismissed
Szia!

Szuper, köszi szépen! Approve-oltam is, mehet a merge.

2024-11-30 11:16 UTC, NagyIstvanGabor approved these changes
Szia!

Volt egy kis fennakadás a reqirements.txt-vel, de megoldódott. approve-oltam újra. köszi!

2024-11-30 11:17 UTC, nistvangabor approved these changes

2024-11-30 15:44 UTC, merged