vancsikpeti\homework08
Global-rd/python_hu pull request #270
Opened 2024-11-26 17:09 UTC by vancsikp

2024-11-28 09:35 UTC, NagyIstvanGabor requested changes
Szia!

Szuper a házid, egy apró megjegyzést adtam csak hozzá a kódhoz, erre nézz rá kérlek.
A deploy-olt verzió linkjét is add hozzá légyszi a PR-hoz egy kommentben. 
Köszi szépen!

2024-11-28 09:35 UTC, NagyIstvanGabor commented on homeworks/vancsikpeti/8_streamlit/weather_data_api.py
> +def get_data(city, method): # method: weather, forecast
nagyon szuper hogy egyben kezeled a forecast-ot és a weather-t!

2024-11-29 12:51 UTC, vancsikp commented
Szia István! A házihoz tartozó deploy-olt verzió linkje: 
https://howistheweatherpeter.streamlit.app/

2024-11-29 13:01 UTC, vancsikp commented on homeworks/vancsikpeti/8_streamlit/weather_data_api.py
> +    coordinates = get_data(city=city, method="weather")["coord"]
Ezt nem értem. Nem tudom hogy induljak el. Itt a get_data() function-nek kellene visszaadnia két értéket: 
result weather, forecast -> ebben az esetben nem tudom, hogy használom fel később a változókat?
vagy kellene egy új osztályt létrehoznom, amiben külön objektum a weather és a forecast?
vagy úgy kellene működnie, mint a 14. óra working_with_df.py-ban a categorize_stock-nak?

2024-11-29 17:32 UTC, NagyIstvanGabor requested changes
Szia!

Ne haragudj, egy kicsit fogalmazhattam volna bővebben. Egyszerűbbre gondoltam:
![image](https://github.com/user-attachments/assets/e10c1331-c4b7-4cf3-9604-2fc1417420be)

![image](https://github.com/user-attachments/assets/b1f967ff-f425-4a19-8647-1d34b8eaddcc)

Annyit egyszerűsítenék, hogy mivel a vizualization_streamlit.py-ban már alapból megkapod a current_weather()-t a get_data()-ból, simán átadhatnád ezt az adatot a function-öknek. 
Így semmi más dolguk nincs, mint kivenni a megfelelő értéket az adatból amit átadsz nekik. Caching-re sincs így szükség.

2024-12-01 14:59 UTC, NagyIstvanGabor approved these changes
Approve-oltam is, köszi!

2024-12-01 16:07 UTC, merged