gaalistvantamas/homework-8
Global-rd/python_hu pull request #272
Opened 2024-11-26 18:30 UTC by GaalIstvanTamas

https://gaalistvantamas-weather-app-weather-app-h4f85s.streamlit.app/

2024-11-28 09:46 UTC, NagyIstvanGabor requested changes
Szia!

Szuper a házi. Egyetlen egy dolgot szeretném ha javítnál, ez pedig a fetch_weather_data() és a fetch_forecast_weather_data(). Ez a két function gyakorlatilag ugyanazt csinálja, csak eltérő endpoint-okkal. Ez az endpoint lehetne egy paraméter és általános fetch_data function-ben, és akkor mind a kettőt le tudná kezelni egyetlen function. Látom, hogy a ttl eltérő a cache-ben, de simán adhatod a forecast-nak is az 1 órás ttl-t.

Köszi szépen!

2024-11-29 16:24 UTC, GaalIstvanTamas commented
Szia, arra gondoltam, hogy igazából elég egy várost adni paraméternek és lekérni az ahhoz tartozó időjárás és előrejelzés adatokat, mert egy városhoz tartozó adatokat jelenítünk meg. Amennyiben ez így jó lesz, akkor a community cloudon is frissíteni kell?

2024-11-29 17:48 UTC, NagyIstvanGabor requested changes
Szia!

Ez így nem a legjobb megoldás, így most egyszerre csinál két dolgot a function-öd. Tanultunk a single responsibility elvről, az itt most nem teljesül. Az lenne a cél, hogy egy function egyszerre egy dolgot csináljon, és a bemeneti paraméterek határozzák meg a végeredményt. Sokkal könnyebb az így megírt function-ökre teszteket írni, és olvashatóság/fenntarthatóság szempontjából is előnyösebb. Ha megnézed akkor a kódod is ugyanaz a két endpoint-ra egymás alá írva. Írd meg kérlek úgy, hogy az endpoint egy paraméter legyen, és csak simán helyezd egy f-stringgel az url-be amire a requestet küldöd. Így két változót csinálsz majd ennek a function-nek az eredményéből, egyet a jelenlegi időre, egyet az előrejelzésre, és ezekkel külön külön tud dolgozni a kód többi része. 
A kérdésedre a válasz igen, a community cloud-on is frissítsd majd kérlek. Köszi szépen!

2024-11-29 18:39 UTC, GaalIstvanTamas commented
Igen, így tényleg szebb. :) Elég ha módosítom a kódot a másik repo-ban vagy van a streamlit oldalán frissítés?

2024-11-29 18:42 UTC, NagyIstvanGabor approved these changes
Szia! Elég ha push-olod a másik repo-ba is ezt a változtatást, frissíteni fogja magától.
Ha valamiért mégsem, akkor alul Manage App -> 3 pötty, Reboot app.

Approve-oltam, köszi szépen! Mehet a merge.

2024-11-29 18:44 UTC, merged