Zsoltcsengeri/homework 8
Global-rd/python_hu pull request #278
Opened 2024-11-27 00:47 UTC by zsoltcsengeri

2024-11-28 10:09 UTC, NagyIstvanGabor requested changes
Szia!

Szuper a házi, nagyon tetszik hogy beleraktad a feels like-ot is!
Egy apróságot írtam kommentben, ezeket nézd át kérlek és javítsd. 
Ezen felül az app_url.txt szuper hogy benne van a repo-ban, de ne a repo root-jába tedd, hanem legyen ez is része a házid mappájának kérlek.
A requirements.txt pedig ide nem kell, ha van esetleg új dependency amit telepítettél, akkor azt a root-ban lévő requirements.txt-hez add hozzá.
Köszi szépen!

2024-11-30 13:36 UTC, zsoltcsengeri commented
Köszi szépen a feedback-et. Megcsináltam a változtatást, kitöröltem a print file-t ami valóban a teszt miatt maradt ott😀

2024-11-30 18:35 UTC, NagyIstvanGabor approved these changes
Szia!

Approve-oltam is, köszi! Mehet a merge.

2024-11-30 18:36 UTC, nistvangabor approved these changes

2024-11-30 19:45 UTC, merged