Nemethmate homework 8
Global-rd/python_hu pull request #279
Opened 2024-11-27 09:13 UTC by Methmat

2024-11-28 10:15 UTC, NagyIstvanGabor requested changes
Szia!

Van a PR-odban egy secrets mappa, benne egy üres secrets.toml-lel. Ezt töröld kérlek:
![image](https://github.com/user-attachments/assets/d7326ee3-6b26-4325-8d92-528f6096df96)
Magában a kódban hagytam néhány megjegyzést, de egyébként a házid szuper. Add még hozzá kérlek a deploy-olt appod linkjét is a PR leírásához. Köszi!

2024-11-28 10:15 UTC, NagyIstvanGabor commented on homeworks/nemethmate/8_streamlit/app.py
> +secrets_path = r"C:\Users\veszperenyine\Documents\GitHub\python_hu\homeworks\nemethmate\8_streamlit\secrets.toml"
ezt a streamlit magától megcsinálja, ha van egy .streamlit mappa a repo-ban, és abban van egy secrets.toml.
ezután úgy tudsz hivatkozni a secret-re ahogy az órán is tanultuk.

2024-11-28 10:15 UTC, NagyIstvanGabor commented on homeworks/nemethmate/8_streamlit/app.py
> +    url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}&units=metric"
szuper lenne, ha maga az api hívás egy function-ben lenne. ezt a function-t pedig tudnád cache-elni, hogy ne fusson le mindig ugyanarra a városra a hívás. Az órai anyag alapján szintén át tudod ezt a részt alakítani.

2024-11-28 10:15 UTC, NagyIstvanGabor commented on homeworks/nemethmate/8_streamlit/forecast.py
> +def get_forecast(city, api_key):
Na pontosan erre gondoltam feljebb, amikor mondtam hogy kell egy function amit cache-elni tudsz.
Alakítsd át ezt a functiont úgy, hogy az endpoint (weather vagy forecast) az url-ben egy paraméter legyen a functionnek. Így a city mellett kelleni fog ennek a functionnek egy endpoint paraméter is. Ezt pedig tudod cache-elni úgy ahogy az órán tanultuk.

2024-11-30 12:01 UTC, Methmat commented
Szia. Elvileg comitoltam de valamiért nem jelent meg a gitben h pusholjam. Ilyen még nem volt. Elkészítettem a módosításokat de nem látom így hogy feltöltötte volna...

https://github.com/Global-rd/python_hu/commit/7bb8f99b082432884955a611cf4922339a576fc1

Nem tudom te így látod e

Köszi

2024-12-01 15:06 UTC, NagyIstvanGabor requested changes
Szia!

Látom a változtatásokat, viszont még mindig van pár dolog ami nincs a helyén:
- van egy secrets mappád amiben benne van a secrets.toml, benne a te api kulcsoddal. Ez is része a PR-nak. Ezt töröld teljesen kérlek, ez nem lehet része a verziókövetésnek.:
![image](https://github.com/user-attachments/assets/1428f2c9-1bb6-429f-a09f-caf43d58780d)

Szuper hogy megírtad a general function-t a forecast.py-ban, de nem használod sehol.
A forecast.py nem egy jó elnevezés ennek a file-nak, mert semmi köze a forecast-hoz, egy általános használatú function van benne.

Az app.py 46. során még mindig simán elküldöd a requestet, itt kéne használnod ezt a function-t amit írtál. 

A 34. soron még mindig ott van egy hard code-olt absolute path a te gépedhez. 
Kérlek az órán tanult módon olvasd be a streamlit-es secret-eket. (legyen egy .streamlit mappa a root-ban, abban egy secrets.toml) a beolvasás pedig ennyi:
https://github.com/Global-rd/python_hu/blob/c310ca5b2e46d671ffc63929f9ce90a872e0b81f/lessons/16/stock_dashboard.py#L7

ezeket változtasd meg kérlek, és approve-olom. köszi!

2024-12-05 08:50 UTC, NagyIstvanGabor approved these changes
Szuper, köszi szépen! Approve-oltam is.

2024-12-05 09:05 UTC, merged