Karolina Valko homework 08
Global-rd/python_hu pull request #281
Opened 2024-11-27 15:08 UTC by KarolinaValko

Mihelyt sikerul a deployolas mar rakom is be a linket. A kod az alaphazival van meg, bar az extrat is elkezdtem, de nem maradt idöm sajna.

2024-11-27 18:53 UTC, KarolinaValko commented
Kesz es mukodik is! Koszonom szepen!

2024-11-28 10:19 UTC, NagyIstvanGabor requested changes
Szia!

Örülök, hogy sikerült megoldani! Egy apróság, ha már betetted a fetch_forecast_city() function-t. Ha megnézed, akkor ez, és a fetch_weather_city() szinte ugyanaz. Egyetlen eltérés az endpoint (weather vagy forecast). Ebből tudnál csinálni egy általánosabb function-t, ami paraméterként kapja meg az endpoint-ot, és lekezeli mindkét esetet. A cache miatt nem kell aggódni, erről írtam a technikai kérdések channel-ben tegnap este. 
https://discord.com/channels/1278691503149158410/1278691503366996112/1311456249920884868

köszi szépen!

2024-11-29 15:59 UTC, KarolinaValko commented
@NagyIstvanGabor : Gondoltam csinalok egy get_response data (url)-t ahova a response = request-töl lefele mindent berakok es akkor a cache-elesnel a return mehetne ezzel. Igenam, de a current weather miatt bukik a dolog es nem tudom hogyan kellene atirnom hogy tudjam aztan hasznalni. Mert a curretnt_weather_data-t kesöbb list-e alakitom es indexelve adom at az oszlopoknak. Szoval nem igazan tudom hol nezem be. Tudsz valami tippet adni? 

Gondolkodtam azon is hogy a URL-eket rakom egy helyre, de aztan meg nem tudom hogy hivjam meg :-/
def fetch_weather_city(city, url):
    finalurl = f'{url}q={city}&appid={API_KEY}&units=metric'
    response = requests.get(finalurl, headers={"Authorization": f"Bearer {API_KEY}"})
    if response.status_code == 200 and url == FORECAST_URL:
        return forecast_weather_data(response.json())
    if response.status_code == 200 and url == WEATHER_URL:    
        return current_weather_data(response.json())
    else:
        st.warning(f"This city is not in our database. Please try another city for weather forecast.")
        return None

2024-11-29 19:36 UTC, KarolinaValko commented
Szioka! No, itten van. Szoval ez elegge challenging volt, de itt van friss - ropogos. Ha beutöd Vittinge -t., en itt lakom :-)
Az SQLs resz az nincs meg, de eselytelen 48 oran belul abszolvalnom sajna. Ha igy is jo SQL nelkul azt megkoszonom :-)

2024-11-30 08:58 UTC, KarolinaValko commented
Na csak sikerul a vegere. Valami szep megoldast akartam, aztan tulbonyolitottam. Köszönöm a segitseget!

2024-11-30 11:19 UTC, NagyIstvanGabor approved these changes
Köszi szépen a gyors változtatást! Approve-oltam is, mehet a merge.

2024-11-30 13:53 UTC, merged