dobrikbartaeva/homework-8
Global-rd/python_hu pull request #283
Opened 2024-11-27 20:05 UTC by evadobrik

szia!

Elkészült a házim, de végül  a forecastos részt nem csináltam meg csak a "kötelezőt":
https://pytonprapp-byculvxatjmqnfhpe4gxby.streamlit.app/

2024-11-28 10:26 UTC, NagyIstvanGabor requested changes
Szia!

Szuper a házid, viszont ahogy beszéltük Discord-on az a jó megoldás amit először csináltál. Egy generic function, ami kezeli mindkét endpointot. 
Nem szükséges a a két külön plusz function ami meghívja ezt, mert a cache-elés figyelembe veszi a paramétereket is. Erről írtam részletesen Discordon, de szerintem azóta még nem láttad, elég későn válaszoltam. 
Ezt az apróságot változtasd meg kérlek és approve-olom is. Köszi szépen!

2024-11-28 12:46 UTC, evadobrik commented
Köszönöm, javítottam.

2024-11-29 16:26 UTC, NagyIstvanGabor requested changes
Szia!

Még a cache_data dekorátor hiányzik a fetch_data()-ról. Ezt még add hozzá kérlek és approve-olom. Köszi szépen!

2024-11-29 16:37 UTC, evadobrik commented
hozzáadtam, köszi!

2024-11-30 11:26 UTC, NagyIstvanGabor approved these changes
Szia!

Approve-oltam, köszi szépen!
Azt írja hogy van egy conflict-od a requirements.txt-vel. Tedd kérlek a következőt:
Kattints rá hogy Resolve conflicts. Megjelenik a szerkesztő, ide másold be a requirements.txt tartalmát a main branchről: https://github.com/Global-rd/python_hu/blob/main/requirements.txt

Utána menj rá hogy "mark as resolved", és commit. Ezután újra kell majd approve-olnom, de ez nem befolyásol semmit a pontjaidon. Köszi szépen!

2024-12-02 12:02 UTC, evadobrik commented
Köszönöm! Remélem így már jó lesz :)

2024-12-05 09:01 UTC, merged