Homework-9
Global-rd/python_hu pull request #302
Opened 2024-12-03 21:15 UTC by szabig

9. Házifeladat első verziója

2024-12-05 09:02 UTC, NagyIstvanGabor requested changes
Szia!

A pydantic és a db modell-t kérlek kezeld egy külön python file-ban. Most még egész olvasható, mert rövid a kód, de szeretném ha az rögzülne bennetek hogy ezt szépen modulárisan kezelitek. Külön a modellek és külön az applikáció logika. Később ez sok fejfájástól meg fog kímélni. Köszi szépen!

2024-12-07 15:56 UTC, NagyIstvanGabor requested changes
Szia!

Most a main.py teljesen üres. Javítsd kérlek. Köszi szépen!

2024-12-07 18:35 UTC, szabig commented
Fú, ebbe a verziókövetésbe néha bele tudok bonyolódni. Megint feltöltöttem és megint üres volt, úgyhogy most itt a Githubon másoltam bele a kódot. Végül így, de megvan. :)
Az kavar meg, ha mellette másik házin másik branch-en is dolgozok és azt is beadom. Ebben az esetben a 10-es házit is leadtam, és vannak még GitHubos dolgok amik összezavarnak. :)

Na de elvileg így most már jó kell, hogy legyen!

2024-12-09 19:23 UTC, NagyIstvanGabor approved these changes
Szia!

Igen, így már stimmel. Köszi szépen!

2024-12-10 14:53 UTC, merged