8th homework
Global-rd/python_hu pull request #303
Opened 2024-12-03 21:25 UTC by DanTar93

2024-12-05 09:06 UTC, NagyIstvanGabor requested changes
Szia!

Vannak pydantic modelljeid definiálva a fastapi_homework.api.py-ban is (itt a filenévből kérlek ezt a pontot töröld, és legyen inkább underscore), és a models.py-ban is. Picit eltér a név és a típusok, de alapvetően a models.py-t kéne használni, és a fastapi_homework_api.py-ban ne is legyen modell definíció. 
Itt figyelj kérlek, hogy ne kombináld a camelCase-t és a snake_case-t az elnevezésnél.

Ezeket változtasd meg kérlek, és approve-olom is.

2024-12-05 18:58 UTC, DanTar93 commented
Szia!
Köszönöm az észrevételeidet! Javítottam a kódomon. Pár perccel ezelőtt commitoltam, viszont nem jelent meg itt pull request.

2024-12-06 18:34 UTC, NagyIstvanGabor requested changes
Szia!

Van még néhány hiba amit javítani kéne. A részleteket megírtam kommentben. Köszi!

2024-12-06 18:34 UTC, NagyIstvanGabor commented on homeworks/taridaniel/9_fastapi/fastapi_homework_api.py
> +class HouseholdAppliancesRequest:
A HouseholdAppliancesRequest és a HouseholdAppliancesResponse ebben a file-ban ne legyen definiálva, mert felülírod vele a rendes Pydantic model-t amit a models.py-ban írsz. Ezzel így el sem fog indulni az app. töröld ezt a két class-t kérlek.

2024-12-06 18:34 UTC, NagyIstvanGabor commented on homeworks/taridaniel/9_fastapi/fastapi_homework_api.py
> +from models import HouseholdAppliances, HouseholdAppliancesResponse, HouseholdAppliancesResponse
Itt kétszer importálod be ugyanazt, az egyik a request model kéne legyen

2024-12-06 18:34 UTC, NagyIstvanGabor commented on homeworks/taridaniel/9_fastapi/fastapi_homework_api.py
> +@app.post("/products/", response_model=HouseholdAppliancesResponse)
figyelj hogy ebben a file-ban több helyen is `HouseholdAppliancesRequest`-et használsz, de a models.py-ban nem így hívod, ott nincs s betű az Appliance után. Ezeket egységesítsd.

2024-12-08 15:48 UTC, DanTar93 commented
Szia!
Köszönöm a kommentjeidet! Változtattam a kódomon újra.

2024-12-09 19:29 UTC, NagyIstvanGabor approved these changes
Szia!

Köszi szépen a változtatásokat, approve-oltam is. Mehet a merge.

2024-12-09 19:46 UTC, merged