Boroczpeter/homework 9
Global-rd/python_hu pull request #307
Opened 2024-12-04 09:55 UTC by boroczp

Szia István!
Ahogy discordon is írtam, megakadtam. Jól jönne valami tanács.
Köszi

2024-12-04 14:00 UTC, boroczp commented
Ha az adatokból kimásolok egy UUID4 típusú ID-t és megpróbálok deletelni vagy updatelni, 404-es hibát dob fel a VSC terminálon. Csak ennél a kettőnél azonosítom az egyedet az id-val. Ennek mi lehet az oka? Mit írhattam el?

2024-12-05 09:46 UTC, NagyIstvanGabor requested changes
Szia!

![image](https://github.com/user-attachments/assets/67298fb1-88cd-447e-9e23-d14da2fdfe66)
Talán így a legkönnyebb megmutatni a megoldást. Az volt a baj, hogy nem stringként kezelte az id-t. Egy sima típuskonverzióval megoldódott a probléma.
Illetve ne felejtsd törölni a context managert amit discordon írtam (oda is raktam egy kis jelet)

2024-12-05 11:39 UTC, boroczp commented
Szia!

Köszönöm, ezek olyan apróságok, amiket utólag csak nehezen találtam volna meg.
Javítottam és töröltem a context managert is.

Még egyszer köszönöm

2024-12-06 20:30 UTC, boroczp commented
Szia!
Igen, ezt én is láttam a githubon, nem tudom hogyan került bele. Elnézést.
![git](https://github.com/user-attachments/assets/22316847-4fda-49c2-b495-20db05f7f3ad)
Most elvileg jónak kell lennie.

2024-12-07 11:32 UTC, boroczp commented
Szia!
Bevallom ebbe most belekeveredtem 🙁 mindent úgy csináltam ahogy leírtad, aztán megjelent hogy 79 változtatást szeretett volna bemerge-lni a mainbe utána meg megjelent a push, felül pedig már 130 fölötti darabszámba szeretett volna pusholni. Megőrülök...
![kép](https://github.com/user-attachments/assets/e0866239-6ac3-410a-9ead-62dfdabbfc38)
Azért látod 68-nak mert közben egyesével discardoltam a changeseket.

Beléptem a github desktop terminálba, ahol ez fogadott:
![kép](https://github.com/user-attachments/assets/2434da45-1d62-4988-9055-5c33d995e940)

Mit csinálok rosszul??

2024-12-07 15:54 UTC, NagyIstvanGabor commented
> Szia! Bevallom ebbe most belekeveredtem 🙁 mindent úgy csináltam ahogy leírtad, aztán megjelent hogy 79 változtatást szeretett volna bemerge-lni a mainbe utána meg megjelent a push, felül pedig már 130 fölötti darabszámba szeretett volna pusholni. Megőrülök... ![kép](https://private-user-images.githubusercontent.com/182505116/393505776-e0866239-6ac3-410a-9ead-62dfdabbfc38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1ODcwNTQsIm5iZiI6MTczMzU4Njc1NCwicGF0aCI6Ii8xODI1MDUxMTYvMzkzNTA1Nzc2LWUwODY2MjM5LTZhYzMtNDEwYS05ZWFkLTYyZGZkYWJiZmMzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QxNTUyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDZhMjQ5Y2RhOWU3YWYwZmUwZTcwZjJiMTNmZWNjNTI4ZTA2YjAwNDhhMjRkMjkxMjU0MWQ3N2JkNTgzMDhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZhlpxASu0GKZXi0j4LuNYRzF5Y_kaprANo8IcTk2WKk) Azért látod 68-nak mert közben egyesével discardoltam a changeseket.
> 
> Beléptem a github desktop terminálba, ahol ez fogadott: ![kép](https://private-user-images.githubusercontent.com/182505116/393505675-2434da45-1d62-4988-9055-5c33d995e940.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1ODcwNTQsIm5iZiI6MTczMzU4Njc1NCwicGF0aCI6Ii8xODI1MDUxMTYvMzkzNTA1Njc1LTI0MzRkYTQ1LTFkNjItNDk4OC05MDU1LTVjMzNkOTk1ZTk0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QxNTUyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzE4N2IzYjUxYzdmMzRmZmEyNDk3YmY3YmY1NGYzNDk4ZjE3ZTk2M2Y0NTc5ZmFkNzEyYmYzNWQ2YzY2ZTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ndt7-XhB_KerDIZUNF_uybGWs6T3xN6AkaOWK5MFJO8)
> 
> Mit csinálok rosszul??

Szia!

Nem pontosan látom át a probléma forrását, így azt javaslom hogy csinálj egy teljesen új branch-et. Menj át a main-re, fetch, pull. Aztán Ebből csinálj egy homework9_2 vagy valami hasonló branch-et. Másold be ide csak és kizárólag a 9_fastapi mappát a háziddal a megfelelő helyre (előtte az előző branch-ről csak ezt a mappát valahova másold ki), és nyisd meg a PR-t. Ezután ezt a PR-t törölheted is.

2024-12-07 16:42 UTC, closed without merging