Frank Toth - Homework 9
Global-rd/python_hu pull request #308
Opened 2024-12-04 16:20 UTC by stFrank79

Szia!

Egyelőre eddig jutottam. Ez azért már elég kemény dió nekem. 

Üdv:
Frank

2024-12-05 09:58 UTC, NagyIstvanGabor requested changes
Szia! Semmi gond, ez valóban egy kicsivel összetettebb feladat, de nem jársz messze a kész állapottól!
Ezeket csinálnám a helyedben:
1. webshop_db.py jelenleg üres, igazából ide úgy ahogy van bemásolhatod az órai anyagot, csak a DATABASE_URL-t írd át (movies helyett amit szeretnél).
2. hozd helyre az importokat (más neveket használsz, mert benne van a "webshop" prefix a file-jaid nevében. illetve az "Optional"-t véletlenül a pydantic-ből is importolod.

Ha ezek megvannak, gyakorlatilag készen is vagy, minden endpoint-od működni fog. Kitartás! :)

2024-12-06 18:40 UTC, NagyIstvanGabor requested changes
Szia!

Bent maradt az Optional importálása (tévesen a pydantic-ből) és így nem indul el az app. Ezt töröld kérlek és approve-olom is. Írtam kommentet hogy hol a hiba.

2024-12-06 18:40 UTC, NagyIstvanGabor commented on homeworks/franktoth/9_fastapi/webshop_model.py
> +from pydantic import BaseModel, Optional
ezt az Optional-t töröld és hibátlan lesz. ezt alatta a typing-ból importáljuk.

2024-12-08 21:26 UTC, stFrank79 commented on homeworks/franktoth/9_fastapi/webshop_model.py
> +from pydantic import BaseModel, Optional
Szia!
Bocs ezt elnéztem tényleg. Köszi szépen, javítottam.
Üdv:
Frank

2024-12-09 21:11 UTC, merged