First homework
Global-rd/python_hu pull request #33
Opened 2024-09-25 21:13 UTC by szabig

2024-09-26 07:18 UTC, NagyIstvanGabor reviewed
Szia!

A feladat megoldásod tökéletes, de kérlek a PR-od címében szerepeljen a neved valamilyen formában, akár ugyanúgy ahogy a branch neve, vagy Homework1-Gesztes Szablcs stb.
Ezt itt githubon is meg tudod tenni ha az Edit gombra kattintasz a PR címe mellett.
Köszi szépen!

2024-09-26 15:33 UTC, szabig commented
Szia! Rendben, megváltoztattam a PR címét! Köszönöm!

2024-09-26 15:48 UTC, NagyIstvanGabor requested changes
Szia, köszi hogy megváltoztattad a PR címét! 
Tegnap este egy apróság elkerülte a figyelmem, a mappa struktúrád nem stimmel. A szabolcsgesztesi mappán belül még kéne legyen egy 1_introduction nevű mappa, és abban kell legyen a .py file. 
Ezt még változtasd meg kérlek, és megy az approve. Köszi!

2024-09-28 14:32 UTC, szabig commented
Szia István!

Upsz tényleg. Létrehoztam a könyvtárat majd abba áthúztam a .py-t. Ezután csak egy Commitot nyomtam, Push lehetőségét nem ajánlotta fel. Úgy látom ez így most jó lesz, mert egyesíti ugyanabban a Pull Requestben az eddigi összes Commitomat ugye? :)

Bevallom egy kicsit még szokni kell ezt logikát. A Commit és a Pull Request már tiszta, ami még mindig megkavar az a Push request. Pontosan mikor van szükség Push requestre a "local repo" oldalról? 

Köszönöm a választ! :)

2024-09-28 16:16 UTC, NagyIstvanGabor approved these changes
Szia!

Köszi szépen a változtatást, így max pontos a feladatod.

A kérdésedre válaszolva: 
"Úgy látom ez így most jó lesz, mert egyesíti ugyanabban a Pull Requestben az eddigi összes Commitomat ugye? :)" - Ez pontosan így van :) Amíg nincs bemerge-ölve egy pull request, addig minden változtatás amit commit-olsz (és aztán push-olsz a remote-ra), hozzáadódik a pull request-edhez.

Ezért furcsa picit az, hogy a push lehetőségét nem ajánlotta fel, mégis látjuk a változást a remote-on.
A commit-tal csak local-ban mentesz egy verziót a változtatásról, a push az ami ezt továbbítja a remote-ra. A push tehát arra jó hogy a local-on lévő változtatásokat (amiket commit-oltál, tehát kvázi egy mérföldkövet hoztál létre), elérhetővé tedd a remote-on (github). Ha nincs nyitva pull request, akkor szimplán a commit-ok hozzáadódnak a branched-hez, ha van nyitva PR, akkor ezt a PR-t fogod updatelni a push-sal.

Ha gondolod ellenőrizd le, ne merge-öld még be a branched, írj a main.py-ba egy új sort (printelj ki valami random dolgot), commit-olj, és nézd meg hogy felajánlja e a push-t (fel kéne neki :) ). Ha tudsz push-olni, nyugodtan nyomj rá, updatelni fogja a PR-t de nyomok rá újra egy approve-ot. Ha mégsem, jelezd itt és megnézzük.

2024-10-03 17:40 UTC, merged

2024-10-03 18:32 UTC, szabig commented
Szia István! 

Köszönöm a részletes választ a Pushról!
Így már éthető a mechanizmus, a gyakorlatban meg tuti biztos benéztem valamit egy kis izgulás közben. :) Vagy lehet az zavart meg, hogy ugye legelöször csak "Publish" volt, nem "Push", és azt kereste a szemem újra... Na mind egy is, működött, a következő házifeladatnál majd újra megfigyelem a lépéseket, immár helyesen.

Egyébként, csak hogy lássam az egészet minden oldalról, és hogy gyakoroljak, az lett a vége, hogy csináltam a GitHubon egy teljesen új privát Repo-t magamnak, amire meghívtam egy másik magamat, és azzal tesztelgetem a Commit/Push/Pull requesteket. Hát persze, hogy ott volt a Push. :)

Szép estét!