Create homework01.py
Global-rd/python_hu pull request #39
Opened 2024-09-28 15:11 UTC by gzlinsz

2024-09-28 16:26 UTC, NagyIstvanGabor reviewed
Szia!

A feladatod tökéletes, viszont a mappa struktúrád nem stimmel. Direktben a zliszkygyorgy mappában van a homework01.py, a helyes struktúra viszont ez kéne legyen:
zlinszkygyorgy/1_introduction/homework01.py. Így minden beadott házi külön mappába kerül. Add hozzá kérlek ezt a plusz mappát, és megy az approve. Köszi szépen!

2024-09-28 22:10 UTC, gzlinsz commented
Szia, módosítottam.

2024-09-28 23:18 UTC, NagyIstvanGabor requested changes
Szia!

A te file-od mostmàr jò, de ezzel együtt töröltèl 24 màsik file-t is. Ha megnèzed a "Files changed" tab-ot felül, 25 file vàltoztatàsàt merge-ölnènk be a main-be. Ebből 1 a te hàzid hozzàadàsa, 24 a többiekè törlèse.
Nyiss kèrlek egy olyan pull requestet, ahol csak a te hàzid a vàltoztatàs. Ehhez a legegyszerűbb ha a master-t bemerge-ölöd a te branch-odba, ìgy minden törölt file-t visszakapsz, ès a tièd is megmarad.
Köszi!

2024-09-29 14:19 UTC, gzlinsz commented
Szia, kérlek nézd majd meg. Sokat próbálkoztam, ezért lehet hogy generáltam pár request-et ami nem volt szándékos. Úgy látom a localban már a jó struktúra van.

2024-09-30 08:50 UTC, NagyIstvanGabor commented
Szia!

Sajnos nem stimmel, nagyon sok file-t törölsz ebben a request-ben, és összesen 1 file-t kéne hozzáadnod. 
Csatolok egy screenshot-ot, ezen láthatod hogy 29 file módosítását próbálod ezzel a request-tel bemerge-ölni:
![image](https://github.com/user-attachments/assets/8bf6ef26-9ad9-4f83-bad3-fd33ecf27621)

Itt normál esetben 1 file-nak kéne lennie, ami a házi feladatod hozzáadását jelenti.
A leggyorsabb megoldás az lenne, hogy mivel ezen a mostani branch-en ahol dolgozol elég kaotikus a helyzet a törlésekkel, kimásolod a házi feladatod valahova, mondjuk az asztalodra. Ezután töröld ezt a branch-et úgy ahogy van.
Hozz létre egy másik branch-et a main alapján, és itt a megfelelő mappastruktúrával (zlinszkygyorgy/1_introduction/homework01.py) hozd létre a házidat (másold ide az asztalról a file-t). Ha ez megvan, mehet a commit, a push, és a pull request (új pull request kell mert már másik branch-on leszel). Köszi!

2024-09-30 12:22 UTC, closed without merging