Create homework1001.py
Global-rd/python_hu pull request #54
Opened 2024-10-01 10:16 UTC by jonasnikolett90

2024-10-01 11:22 UTC, NagyIstvanGabor reviewed
Szia! Tökéletes a házid, viszont kérlek a PR nevét változtasd meg úgy, hogy benne legyen a neved. Jónás Nikolett - Create homework 1001.py például. A lényeg h már a PR listából látszódjon hogy kihez tartozik. Ha ez megvan, max pont és megy az approve. Köszi szépen!

2024-10-01 20:12 UTC, NagyIstvanGabor requested changes
Szia!

Most 2 python file-od van ami ugyanazt tartalmazza:
[jonasnikolett\homework1001.py](https://github.com/Global-rd/python_hu/pull/54/files#diff-37de5c4147a0a0a0c1ad60bb9e279e6a0607adf8bd80441a2bd521b7b5ddd8cb)
és
[jonasnikolett_homework1001.py](https://github.com/Global-rd/python_hu/pull/54/files#diff-73404075b3dd5777e3eea244fd4e616f7ae5ec650fb6c2e6f3ba3bc1f38c4bb6)

A cél az lenne, hogy a homeworks/jonasnikolett mappában legyen egy 1_introduction nevű mappa, és abban legyen a homework1001.py. 
Félreértettél az előbb, ha jól látom te most a .py file-t nevezted át. A pull request az maga a "felkérés" arra hogy bemerge-öljük a .py file-t a main branch-be.
A pull requested-et így tudod átnevezni:
![image](https://github.com/user-attachments/assets/970f69f8-c976-4778-90a6-4f729748b85c)
Ha erre rákattintasz, át tudod írni a Pull request címét úgy, hogy az tartalmazza a neved.
A python file-ok közül egyet törölj kérlek, és figyelj hogy jelen legyen az 1_introduction mappa is ahogy az előbb írtam.

Köszi szépen!

2024-10-03 15:35 UTC, jonasnikolett90 commented
Szia!

Köszi szépen a visszajelzést! Amikor próbáltam mappába helyezni akkor sikerült még egyet létrehoznom valahogyan.
Remélem így most már jó?
A gépen is látom a mappát és itt is :-)
Valamiért mást láttam a gépen meg itt fent a github-on

Köszi 
Niki

2024-10-03 15:42 UTC, NagyIstvanGabor approved these changes
Szuper, így már max pont, köszi szépen!
Mehet a merge!

2024-10-03 16:01 UTC, merged