asztaloslajos/homework-2
Global-rd/python_hu pull request #56
Opened 2024-10-01 18:39 UTC by AsztalosLajos

2024-10-05 08:44 UTC, NagyIstvanGabor requested changes
Szia!

Nagyon pozitív, hogy már most használsz docstringeket az elején!
Írtam néhány kommentet a kódhoz, de nagy hibáid nincsenek. Viszont láttam, hogy a homework-1 branch-ről nyitottad a PR-t. Írtam erről a discord-ra egy posztot a #fontos-információk- ba. Javítsd kérlek a változtatni valókat, és utána a discord-on leírtak alapján vidd át a változtatásokat egy homework-2 branchre. Ha ezeket javítod, max pont. Szép munka!

2024-10-05 08:44 UTC, NagyIstvanGabor commented on homeworks/asztaloslajos/2_vars_datatypes/fictive_character.py
> +name = name.strip().title()
Nem hiba, csak egy megjegyzés: Ha rövidíteni akarsz a kódon, akkor a .strip().title() method chain mehet a 6. sorra:
name = input("Név:").strip().title()

2024-10-05 08:44 UTC, NagyIstvanGabor commented on homeworks/asztaloslajos/2_vars_datatypes/fictive_character.py
> +age_in_days = (datetime.today()-datetime.today().replace(year=datetime.today().year - age)).days
Ez egy picit megbonyolítja a dolgot, ha azt feltételezzük, hogy ma van a szülinapja. 
Elég lenne annyi, hogy felszorzod az age-et 365-tel. Ha megváltoztatod, akkor az import sem kell.

2024-10-05 08:44 UTC, NagyIstvanGabor commented on homeworks/asztaloslajos/2_vars_datatypes/fictive_character.py
> +print(f"My character is {age_in_days} old. His/her is {name} and he/she has {python_exp_in_years} years experience.")
Itt van egy pici typo, hiányzik a "name" a "His/her" után de még a {name} előtt.

2024-10-05 08:44 UTC, NagyIstvanGabor commented on homeworks/asztaloslajos/2_vars_datatypes/user_info.py
> +user_info["favourite_meals"].append(user_info["favourite_meals"][3])
Itt két külön soron adod hozzá a 3. és 4. elemet. Ez a megoldás működik ugyan, de ha hozzá kéne adni még 10 elemet akkor nagyon erős lenne a kódismétlés. 
Tanultunk az extend method-ról, és arról hogy hogyan érünk el szeleteket a listából. pl: my_list[2:4]. Ezek segítségével meg tudod 1 soron oldani a feladatot.

2024-10-05 08:44 UTC, NagyIstvanGabor commented on homeworks/asztaloslajos/2_vars_datatypes/user_info.py
> +user_info["phone_contacts"]["Tim"]=None
Ezzel nem törlöd ki Tim-et a telefonkönyvből, csak a telefonszáma szűnik meg. Tanultunk a del keyword-ről, annak segítségével el tudnád teljesen távolítani Tim-et.

2024-10-06 09:55 UTC, nistvangabor submitted a review, later dismissed
Szuper, max pont, köszi szépen!
Mehet a merge!

2024-10-06 09:56 UTC, NagyIstvanGabor approved these changes

2024-10-13 17:51 UTC, closed without merging