nagynorbert/homework-2
Global-rd/python_hu pull request #60
Opened 2024-10-02 18:43 UTC by nagynorbi

2024-10-05 14:39 UTC, NagyIstvanGabor requested changes
Szia!

Van 2 hiba a megoldásodban ami miatt nem tudom még approve-olni, az egyik az első és utolsó index felcserélése, a másik az utolsó 3 elem fordítva való kiírása. Ezek a változtatások szükségesek az approve-hoz, a többi csak nice to have. Minden sorhoz odaírtam kommentben a teendőket. Összességében viszont nagy szép munka, köszi szépen! Ha küldöd a változtatásokat határidőig, max pont.

2024-10-05 14:39 UTC, NagyIstvanGabor commented on homeworks/nagynorbert/2_vars_datatypes/fictive_character.py
> +match fict_pro:
Szuper a match-case megoldás, de akkor már vigyük tovább :)
Ha nem "yes"-t vagy "no"-t adok meg, akkor a fict_pro_bool változó nem jön létre, és a program egy NameError-ral elhasal ahol később a 19. soron erre a változóra hivatkozol (a case _-nál csak printelsz). Ezt megoldhatnád úgy, hogy addig kérsz be input-ot amíg nem "yes" vagy "no" a válasz (hétfőn tanulunk erről, de tekintve hogy a match/case-t nem tanultuk, lehet már ismered a while loop-okat pl).
Ez persze nem kötelező, csak ha szeretnél egy kis plusz kihívást.

2024-10-05 14:39 UTC, NagyIstvanGabor commented on homeworks/nagynorbert/2_vars_datatypes/user_info.py
> +user_info["favourite_meals"][0] = "rantott_hus"
Itt a feladat az lenne, hogy úgy cseréld fel az első és utolsó elemet, hogy nem az értékükre hivatkozol, hanem az index-ükre. Ha itt nem rántott hús és somlói van a listában, a mostani kóddal akkor is ezeket az értékeket adnád meg, és az már nem felcserélés, hanem szimplán értékadás.

2024-10-05 14:39 UTC, NagyIstvanGabor commented on homeworks/nagynorbert/2_vars_datatypes/user_info.py
> +fav_meals_l = user_info["favourite_meals"]
itt ezeken a sorokon értem a célod, de ezt le lehet egy picit egyszerűsíteni:
user_info["favourite_meals"] = sorted(list(set(user_info["favourite_meals"])))

2024-10-05 14:39 UTC, NagyIstvanGabor commented on homeworks/nagynorbert/2_vars_datatypes/user_info.py
> +print(user_info["skills"][::-1])
Itt csak az utolsó 3 elemet kéne ellentétes sorrendben kiírni, a jelenlegi megoldásod a teljes listát kiírja ellentétes sorrendben. Egy apró változtatás elég, ami kiválasztja a lista egy szeletét, és aztán ezt írhatod ki ellentétes sorrendben.

2024-10-05 14:39 UTC, NagyIstvanGabor commented on homeworks/nagynorbert/2_vars_datatypes/user_info.py
> +phone_cont_dict = dict(user_info["phone_contacts"])
A user_info["phone_contacts") már alapból egy dictionary, így nem szükséges a dict() típuskonverzió.

2024-10-05 14:39 UTC, NagyIstvanGabor commented on homeworks/nagynorbert/2_vars_datatypes/user_info.py
> +user_info["phone_contacts"].update({"Tim":tim2_tel})
Nincs hiba a megoldásodban, ezt csak szeretném megmutatni, hogy ha esetleg egyszerűsítenéd:
user_info["phone_contacts"]["Tim"] = user_info["phone_contacts"].pop("Tim2")
ugyanazt az eredményt hozza egyetlen 1 soron.

2024-10-05 18:09 UTC, nagynorbi commented
Javítottam őket. Várom a visszajelzésed.

2024-10-06 10:13 UTC, NagyIstvanGabor requested changes
Szia!

2 apró dolog van még, ha ezeket megoldod max pont és megy az approve. Köszi!

2024-10-06 10:13 UTC, NagyIstvanGabor commented on homeworks/nagynorbert/2_vars_datatypes/fictive_character.py
> +while fict_pro not in answer:
Szia, már alakul, de így kétszer írod le ugyanazt a kérdést. Próbáld meg így:
```
while True:
    fict_pro = input("Would your character be a pro Python developer? (Yes/No)").strip().lower()
    if fict_pro in ["yes", "no"]:
        break
    else:
        print("Invalid input. Please answer with 'yes' or 'no'.")
```
Ezzel indítasz egy végtelen ciklust amiből kilépsz a break-kel ha "yes"-t vagy "no"-t válaszol. Holnap tanulunk ezekről bővebben, szóval ez tényleg csak egy nice to have dolog most.

2024-10-06 10:13 UTC, NagyIstvanGabor commented on homeworks/nagynorbert/2_vars_datatypes/user_info.py
> +user_info["favourite_meals"][-1] = first_meal
a megoldásod jó külön külön sorokon, de fölösleges létrehozni a first_meal-t, és a csere 1 történjen 1 soron:
`user_info["favourite_meals"][0],user_info["favourite_meals"][-1] = user_info["favourite_meals"][-1],user_info["favourite_meals"][0]`

Különben ez történik:
```
test = [1,2,3]
test[0] = test[-1]
test[-1] = test[0]
print(test) # [3,1,3]
```

helyesen:
`test[0],test[-1] = test[-1],test[0] # [3, 2, 1]`

2024-10-06 12:32 UTC, nagynorbi commented
Köszi, jól kitalált gyakorló feladatsor volt! 
Javítottam őket.

2024-10-07 07:06 UTC, NagyIstvanGabor approved these changes
Szia! Szuper lett minden, köszi a munkádat!
Approve-oltam, mehet a merge.

2024-10-07 07:07 UTC, merged