2.1 Homework - Fictive Character
Global-rd/python_hu pull request #64
Opened 2024-10-04 15:20 UTC by stFrank79

A második házi első része. Várom a javítási javaslatokat.
Üdv:
Frank

2024-10-05 04:58 UTC, stFrank79 commented
Illetve a második is...

2024-10-05 16:03 UTC, NagyIstvanGabor requested changes
Szia!

Szép munka, van pár apró változtatni való, de ami funckionális hiba az egyedül a phone_contact hozzáadása 2 telefonszámmal, illetve az egymás utáni printek az első feladatban. Mindent leírtam a kommentekben. A PR címébe írd bele légyszi bármilyen formában a neved (itt githubon az edit gomb a cím mellett). Köszi szépen!

2024-10-06 16:41 UTC, stFrank79 commented on homeworks/franktoth/2_vars_datatypes/fictive_character.py
> +db_name = str.capitalize(name)  #captializing the name
Szia!

A db - az database valóban. Az én gondolatmenetemben van egy entry value és egy transzformáció utáni, ami már mehet a db-be. Kb. mint egy data cleansing & enrichment lépés utáni érték.
Javítottam a name formázást.

2024-10-06 16:49 UTC, stFrank79 commented on homeworks/franktoth/2_vars_datatypes/fictive_character.py
> +print(f"My character is {db_age_in_days} days old.")
Hát oké, de szerettem volna olvashatóbbá tenni a szöveget. Igy kenyérszövegként jelenik meg és nekem ez nem túl szimpatikus. Ok-ok, látom, ahogy html-ben, Python-ban is /n a sortörés. Igy mindkettőnk vágya teljesült. :)
Javítva

2024-10-06 17:13 UTC, stFrank79 commented on homeworks/franktoth/2_vars_datatypes/user_info.py
> +user_info["phone_contacts"]["Eve2"] = "+49563252765"    #add a new contact with 2 numbers (ez valószínűleg nem jó így)
Oké...igazából az zavart meg, hogy az eredeti phone_contacts dictionary-ban, nincs key to multiple value bejegyzés, hiszen Tim két számához is 2 key tartozik. Szerettem volna ugyanígy eljárni az új contact esetében is.
Javítottam úgy, hogy 1 személy 2 szám.

2024-10-07 07:12 UTC, NagyIstvanGabor commented on homeworks/franktoth/2_vars_datatypes/fictive_character.py
> +db_name = str.capitalize(name)  #captializing the name
Szia! Így már értem. Viszont a db_name változónév inkább hangzik egy adatbázis nevének, mint egy felhasználónévnek ami bekerül a db-be. Ezen persze nem kell változtatnod, csak mint feedback le szerettem volna írni hogy külső szemmel nem biztos h a legkönnyebben értelmezhető változónév.

2024-10-07 07:13 UTC, NagyIstvanGabor commented on homeworks/franktoth/2_vars_datatypes/user_info.py
> +user_info["phone_contacts"]["Eve2"] = "+49563252765"    #add a new contact with 2 numbers (ez valószínűleg nem jó így)
Értem, jogos, én is írhattam volna egyértelműbben a feladatot.

2024-10-07 07:17 UTC, NagyIstvanGabor approved these changes
Szia!

Köszi hogy megcsináltad a változtatásokat, hagytam még 2 kommentet, de ezeket elég ha csak elolvasod a jövőre nézve, amúgy approved a PR.
Köszi szépen a munkádat, mehet a merge!

2024-10-07 07:17 UTC, NagyIstvanGabor commented on homeworks/franktoth/2_vars_datatypes/fictive_character.py
> +prof_dev_decision = "He/She wants to be a prof Python Developer" if user_prof_dev=="yes" else "He/She doesn't want to be a prof developer"
Ez előbb elkerülte a figyelmem, most is csak FYI:
Ha a prof_dev_decision értéke csak annyi lenne hogy "wants" vagy "doesn't want", a többi szöveget be tudnád rakni a print-be, és csak ezeket kellene beágyazni, rövidítve a ternary-t.

2024-10-07 07:25 UTC, merged

2024-10-07 07:25 UTC, stFrank79 commented
Köszi!