boroczpeter - homework 2 - fictive character & user info wo/w extras
Global-rd/python_hu pull request #66
Opened 2024-10-05 00:06 UTC by boroczp

2024-10-05 16:39 UTC, NagyIstvanGabor requested changes
Szia!

Nagyon jó házi feladat, viszont van néhány apróság amin szuper lenne ha tudnál javítani (effektívebb ternary, slicing a felsorolás helyett, tuple a list helyett, mindegyikhez írtam részleteket a megfelelő sorra). Ezeket kérlek nézd át. 
Töröld nyugodtan a fictive_character.py-t és a user_info.py-t, mert ahogy látom az "extra.py" file-ok is tartalmazzák azt amit a sima, és így nem duplikálódik a kódod két különböző helyen. Köszi szépen!

2024-10-05 16:39 UTC, NagyIstvanGabor commented on homeworks/boroczpeter/2_vars_datatypes/fictive_character extra.py
> +#using ternary operator in Boolean variable
Mi lenne, ha a ternary operator nem egy True-t vagy False-t adna vissza, hanem azt a 2 string részletet ami eltér a 2 kiprintelt mondatod között?
"wants" és "does not want". 
Ezt a két értéket vehetné fel a want_to_be_dev változód (vagy ha más nevet adsz neki emiatt, akkor az), és elég lenne egyszer printelned úgy, hogy ezt a változót beágyazod a mondatban a He/she után. Így nem kéne még egy if-else.

2024-10-05 16:39 UTC, NagyIstvanGabor commented on homeworks/boroczpeter/2_vars_datatypes/user_info extra.py
> +skill = input("Write four programming languages separated by a comma, no spacing!: ").split(",") #converting to list at the same time
apróság, de ha olyan változót hozol létre, ami több elemet tartalmaz, érdemes többet számot használni a változó névhez ("skills")

2024-10-05 16:39 UTC, NagyIstvanGabor commented on homeworks/boroczpeter/2_vars_datatypes/user_info extra.py
> +user_info["favourite_meals"].extend([user_info["favourite_meals"][2], user_info["favourite_meals"][3]])
a megoldásod jó, de ha több elemet kellett volna itt hozzáadni, akkor időigényes és ismétlődő lenne mindet egyesével felsorolni. Próbálj slice-okat használni. Pl: user_info["favourite_meals"][2:4]

2024-10-05 16:39 UTC, NagyIstvanGabor commented on homeworks/boroczpeter/2_vars_datatypes/user_info extra.py
> +user_info["favourite_meals"] = list(dict.fromkeys(user_info["favourite_meals"]))
szuper megoldás, hogy fenntartsd a sorrendet!

2024-10-05 16:39 UTC, NagyIstvanGabor commented on homeworks/boroczpeter/2_vars_datatypes/user_info extra.py
> +user_info["phone_contacts"]["Carol"]="+362022222222","+363033333333"
Ezzel így egy tuple-t fogsz kapni, amit később nem fogsz tudni változtatni. Ha törölni kell a telefonszámot pl, akkor ez nem a legjobb megoldás. Egy lista már annál inkább.

2024-10-05 16:39 UTC, NagyIstvanGabor commented on homeworks/boroczpeter/2_vars_datatypes/user_info extra.py
> +user_info["phone_contacts"]["Tim"] = user_info["phone_contacts"].pop("Tim2")
szuper megoldás mindkét extra feladathoz!

2024-10-05 20:34 UTC, boroczp commented
Valamiért kétszer Pulloltam, kicsit macerás még a GitHub kezelése. A VSC-vel már nincs gondom.

2024-10-06 10:31 UTC, NagyIstvanGabor approved these changes
Szia!
Szuperül megoldottál mindent, köszi szépen! Approved, mehet a merge.

2024-10-06 10:44 UTC, merged