homework_2
Global-rd/python_hu pull request #69
Opened 2024-10-05 16:09 UTC by balanagy23

Kötelező és extra feladatok is elvégezve.
Remélem nem zavaró, hogy a feladat leírást bemásoltam nekem segítség, ha probléma törlöm.
Az első feladatnál zavarta piciny lelkemet a kiírás ezért tettem bele egy plusz kérdést, ha ez probléma kérlek jelezd és javítom

2024-10-05 17:49 UTC, NagyIstvanGabor requested changes
Szia!

Semmi gond azzal, hogy bemásoltad a feladat leírást, és a nem megállapításának ötlete is szuper!
Írtam pár kommentet, olvasd át őket légyszi, és utána jöhetnek a változtatások.
Köszi szépen!

2024-10-05 17:49 UTC, NagyIstvanGabor commented on homeworks/nagybalazs/2_vars_datatypes/fictive_character.py
> +name = name.strip().upper()
nem hiba, csak egy megjegyzés: ha szeretnéd, egy soron is meg tudod formázni a bekért nevet:
name = input("What is your name? ").strip().upper()

2024-10-05 17:49 UTC, NagyIstvanGabor commented on homeworks/nagybalazs/2_vars_datatypes/fictive_character.py
> +age_in_days = int(age * 365)
Mivel az age-t is intté alakítod egy sorral feljebb, itt az int() típus konverzió fölösleges. 
Két integer szorzása mindig integert fog visszaadni (szintén nem extra hiba).

2024-10-05 17:49 UTC, NagyIstvanGabor commented on homeworks/nagybalazs/2_vars_datatypes/fictive_character.py
> +python_exp_in_years = int(input("Years of Python experience? "))
baromi jó a változó név választás!

2024-10-05 17:49 UTC, NagyIstvanGabor commented on homeworks/nagybalazs/2_vars_datatypes/fictive_character.py
> +python_dev = str(input("Years of Python experience? Yes or No? "))
Itt biztos ezt a kérdést akarod feltenni?

2024-10-05 17:49 UTC, NagyIstvanGabor commented on homeworks/nagybalazs/2_vars_datatypes/fictive_character.py
> +if python_dev_bool == True:
Ez a komment a teljes if-else struktúrára vonatkozik:

Nagyon király, hogy belevetted a nemet is, és az alapján döntöd el hogy "He"/"his" vagy "She"/"her" kerüljön a kiprintelt mondatba. Az az egy probléma van így a kóddal, hogy 4x leírod szinte ugyanazt. Tanulunk majd a DRY elvről (Don't Repeat Yourself), aminek itt a határait erősen feszegeted :) De nincs ezzel gond, mert van megoldás:
Nézd meg mik a különbségek a 4 verzióban:
He - She
His - Her
wants - does not want

Mi lenne akkor, ha ezeket eltárolnád egy-egy változóban, és egyetlen egy print-be beágyaznád az aktuális értékeket?
Így egy printed van, nem 4, és nem ismétled magad. A sex értéke alapján meg tudod állapítani az első 2 változó értékét, a python_dev alapján pedig a harmadikét.

2024-10-05 17:49 UTC, NagyIstvanGabor commented on homeworks/nagybalazs/2_vars_datatypes/user_info.py
> +prog_skills = str(input("What programming languages ​​do you know? Please give me 4 languages (separator ','):"))
az input() alapból egy string-et ad vissza, nem kell az str()

2024-10-05 17:49 UTC, NagyIstvanGabor commented on homeworks/nagybalazs/2_vars_datatypes/user_info.py
> +user_info["favourite_meals"] = user_info_sorted #a "favourite_meals"-t felülírjuk a user_info_sorted elemeivel
Nem rossz a megoldásod, ez is csak egy megjegyzés, hogy lehet egyszerűbben is:
Mivel a list mutable, meghívhatod rá direktben a .sort() method-ot, és in-place elintézheted a dolgot:
user_info["favourite_meals"].sort()

2024-10-05 17:49 UTC, NagyIstvanGabor commented on homeworks/nagybalazs/2_vars_datatypes/user_info.py
> +user_info["favourite_meals"].extend(user_info["favourite_meals"][2:4])
nagyon szép megoldás!

2024-10-05 17:49 UTC, NagyIstvanGabor commented on homeworks/nagybalazs/2_vars_datatypes/user_info.py
> +user_info["favourite_meals"] = favourite_meals_list
ez is csak megjegyzés, nem probléma:
user_info["favourite_meals"] = list(set(user_info["favourite_meals"]))
így 1 soron ugyanazt éred el.

2024-10-05 17:49 UTC, NagyIstvanGabor commented on homeworks/nagybalazs/2_vars_datatypes/user_info.py
> +(user_info["phone_contacts"])["minime"] = "+3610234345"
itt nem szükséges zárójelezni a dictionary key-t, mehet így:
user_info["phone_contacts"]["minime"] = "+3610234345"

2024-10-05 17:49 UTC, NagyIstvanGabor commented on homeworks/nagybalazs/2_vars_datatypes/user_info.py
> +(user_info["phone_contacts"])["Tim"] = (user_info["phone_contacts"]).pop("Tim2")
szuper a pop-os assignolás, de itt sem kell a zárójel (ahogy az előzőnél jeleztem)

2024-10-05 17:49 UTC, NagyIstvanGabor commented on homeworks/nagybalazs/2_vars_datatypes/user_info.py
> +(user_info["phone_contacts"])["ketteske"] = "+3610234345","+3610234345"
itt sem kell a zárójel, valamint így egy tuple-t adsz hozzá ketteske értékéhez. Tekintve hogy a telefonszám változhat, a tuple nem a legjobb megoldás, egy lista annál inkább.

2024-10-05 17:49 UTC, NagyIstvanGabor commented on homeworks/nagybalazs/2_vars_datatypes/user_info.py
> +print(user_info["skills"][-1:-4:-1])
szuper megoldás!

2024-10-05 18:56 UTC, balanagy23 commented
Köszönöm a visszajelzéseket, a felesleges sorok eltüntetésével tényleg sokkal szebb lett a kód.

2024-10-06 10:34 UTC, NagyIstvanGabor approved these changes
Szia! Nagyon szuperül megcsináltál mindent, köszi szépen!
Approved, mehet a merge!

2024-10-07 05:28 UTC, merged