Schreinerbalazs homework 2
Global-rd/python_hu pull request #84
Opened 2024-10-07 06:44 UTC by snerbalu

2024-10-07 09:23 UTC, NagyIstvanGabor requested changes
Szia!

A mappa struktúrád nem stimmel, az 1_introduction-be tetted a 2_vars_datatypes mappát is, ezek egy szinten kell legyenek.
Ezen felül írtam kommentben néhány apróságot ,ezeket változtasd meg kérlek és megy az approve. Köszi szépen!

2024-10-07 09:23 UTC, NagyIstvanGabor commented on homeworks/schreinerbalazs/1_introduction/2_vars_datatypes/fictive_character.py
> +python_want_to_be = "want to become a Phyton developer." if python_want_to_be == True else "don't want to be a Phyton developer."
Mi lenne ha csak egy ternary kifejezés lenne, ami egyből a két stringet adja értékül a python_want_to_be-nak?
A 14. sor így nem szükséges.

2024-10-07 09:23 UTC, NagyIstvanGabor commented on homeworks/schreinerbalazs/1_introduction/2_vars_datatypes/user_info.py
> +from pprint import pprint
az import-okat kérlek a kód elejére rakd, ez a best practice.

2024-10-07 09:23 UTC, NagyIstvanGabor commented on homeworks/schreinerbalazs/1_introduction/2_vars_datatypes/user_info.py
> +from pprint import pprint
ez az import pedig nem kell, ha már egyszer importoltad a pprint-et

2024-10-07 09:23 UTC, NagyIstvanGabor commented on homeworks/schreinerbalazs/1_introduction/2_vars_datatypes/user_info.py
> +user_info["favourite_meals"].append(user_info["favourite_meals"][2])
a megoldásod működik, de ha 30 elemet kéne így hozzáadni, akkor nagyon ismétlődő lenne. Próbáld meg exted-del és slicing-gal:
`user_info["favourite_meals"].extend(user_info["favourite_meals"][2:4])`
így a slicing visszaad egy listát amit az extenddel hozzá tudsz adni.

2024-10-07 14:47 UTC, snerbalu commented
Hülyét kapok, nem tudom miért nem tudok pool request-elni.

2024-10-07 19:14 UTC, NagyIstvanGabor requested changes
Szia, maga a kód már szuper, és látom hogy mostmár a 2_vars_data_types mappa is jó helyen van, viszont az 1_introduction-ben is ott van még. 
![image](https://github.com/user-attachments/assets/b0ec5c92-aaad-4ea8-8d06-bba30ffd4227)
Kitörölnéd kérlek ezt a verziót? Ha megvan, megy is az approve.
Ha jól láttam, több commit-ot is push-oltál, és írtad hogy nem tudsz pull request-elni. Ha meg van nyitva egy pull request-ed, akkor minden commit és push automatikusan hozzáadódik a pull request-edhez, nem kell újat nyitni, szerintem ez volt a félrevezető.

2024-10-08 16:50 UTC, NagyIstvanGabor approved these changes
Szia, így már szuper a házi, köszi szépen! Approved, mehet a merge!

2024-10-09 06:35 UTC, merged