2nd homework
Global-rd/python_hu pull request #88
Opened 2024-10-07 14:39 UTC by DanTar93

2024-10-07 18:57 UTC, NagyIstvanGabor requested changes
Szia!

A második feladat nagyon szép munka, csak pár apró változtatás miatt írtam néhány kommentet. Az első feladatban kicsit több a hiányosság, ott is jeleztem mindent külön kommentekben. Ezeket változtasd meg kérlek, és megy az approve. Köszi szépen!

2024-10-07 18:57 UTC, NagyIstvanGabor commented on homeworks/taridaniel/2_vars_datatypes/fictive_character.py
> +name = "Daniel Tari"
Ezeket a változókat a felhasználótól kérd be az input() function-nel, és hívd meg rájuk a .strip() és a .capitalize() metódusokat, hogy biztosítsd hogy nincs fölösleges szóköz, és nagybetűvel kezdődik a név!

2024-10-07 18:57 UTC, NagyIstvanGabor commented on homeworks/taridaniel/2_vars_datatypes/fictive_character.py
> +age = "30"
az age is a felhasználótól kell jöjjön input()-tal

2024-10-07 18:57 UTC, NagyIstvanGabor commented on homeworks/taridaniel/2_vars_datatypes/fictive_character.py
> +age_in_days = int(age)*30*365
Ha a 30 az évek száma, akkor az *30 nem kell, elég a *365, különben elég durva szám jön ki :)

2024-10-07 18:57 UTC, NagyIstvanGabor commented on homeworks/taridaniel/2_vars_datatypes/user_info.py
> +#Erre sajnos nem jöttem rá :(
Semmi gond :) 

user_info["favourite_meals"][0], user_info["favourite_meals"][-1] = (
    user_info["favourite_meals"][-1],
    user_info["favourite_meals"][0],
)

Ezzel a kifejezéssel meg tudod oldani az elemek cseréjét. 0 helyére megy a -1, és a -1 helyére a 0. Egy soron van, tehát egyszerre hajtódik végre.

2024-10-07 18:57 UTC, NagyIstvanGabor commented on homeworks/taridaniel/2_vars_datatypes/user_info.py
> +user_info["phone_contacts"].update({"Bob": "+36209876543" "," "+36208765432"})
Értem mi volt a cél, de ezzel így egy string-et adsz hozzá. Erre alkalmasabb lenne egy lista, amiben eltárolod a két telefonszámot.

2024-10-08 19:18 UTC, DanTar93 commented
Szia István!
Köszönöm a visszajelzésedet és a segítséget! Küldöm az új verziót.

2024-10-09 07:57 UTC, NagyIstvanGabor approved these changes
Szuper, köszönöm szépen a változtatásokat!
Approved, mehet a merge!

2024-10-09 15:55 UTC, merged