Frank Toth - Homework 3.1
Global-rd/python_hu pull request #98
Opened 2024-10-09 22:39 UTC by stFrank79

Sarah - Flat Finder

Beleírtam a file-ba is, hogy lehet kissé terjengős lett a megoldás, de a tudásom alapján egyelőre így tudtam megoldani.
Üdv:
Frank

2024-10-10 19:07 UTC, NagyIstvanGabor approved these changes
Szia!

Semmi gond ezzel a megoldással, az eddig tanultak alapján terjengősnek sem nevezném.
Egy kommentet hagytam, de az is csak FYI.
Approve-oltam ha ezt külön szeretnéd bemerge-ölni, és nyitni egy másik PR-t a második feladatra. Ha mégsem, akkor csak push-old ide a 2-est (és remélem az extrát ;) ), csak akkor írd át majd a PR nevét 3.1-ről simán 3-ra.

2024-10-10 19:07 UTC, NagyIstvanGabor commented on homeworks/franktoth/3_conditionals_loops/flat_finder.py
> +if city == "New York" or city == "San Francisco":
nincs baj az or-ral és a két city vizsgálattal, csak mutatok egy másik megoldást is:
`if city in ["New York", "San Francisco"]: `

Ha több város tartozna ebbe a kategóriába akkor érdemes ezeket eltárolni egy változóban, pl:
`loved_cities = ["New York", "San Francisco", "Boston", "San Jose"]`
aztán csak:
`if city in loved_cities:`

Ehhez a feladathoz tökéletes a mostani megoldás.

2024-10-10 19:11 UTC, NagyIstvanGabor commented
Még egy dolog, ez először elkerülte a figyelmem, bocsánat. 
Még mindig a homework-1 branch-et használod, a helyes eljárás az lenne hogy minden új házihoz egy új branch-et hozol létre.
Simán hozz létre egy branch-et franktoth/homework-3 néven, csak ne a main alapján, hanem ez alapján amin most vagy, így simán át tudod oda húzni a mostani változtatásaid.

2024-10-10 19:11 UTC, NagyIstvanGabor requested changes
A fenti kommentem miatt átraktam request changes-re, ha a homework-3 branchről jön a PR, megy is az approve.

2024-10-12 02:36 UTC, stFrank79 commented
Hozzátettem a második házit is és átírtam a PR-t 3-ra.
Oh, most látom csak, hogy másik branchet kell készítenem...bocs, csinálom

2024-10-14 12:17 UTC, NagyIstvanGabor commented
Köszi, átnéztem a homework-3-ról nyitott PR-odat, folytassuk ott tovább kérlek. 
Ezt a PR-t zárd, alul van egy gomb erre. Köszi szépen!

2024-10-21 18:02 UTC, closed without merging