3rd homework + extra exercise - Nagy Norbert
Global-rd/python_hu pull request #99
Opened 2024-10-11 20:20 UTC by nagynorbi

2024-10-14 11:54 UTC, NagyIstvanGabor requested changes
Szia!

Nagyon jól használod a function-öket, az első 2 feladatban van néhány apróság amit lehetne egyszerűsíteni, ebből az egyiket mindenképp javítsd kérlek (ahol fölöslegesen hívod a function-t minden értékadás után, odaírtam kommentben a részleteket). 
A harmadik feladatban is nagyon szépen felbontottad logikailag a feladatot különböző function-ökre, nagyon szép munka! Az extra feladatodnál egy logikai hiba van csak, hogy ha a felhasználó megpróbál egy olyan széket lefoglalni ami már foglalt, akkor kiírod ugyan hogy "already reserved", de nincs lehetőség másikat választani. Mivel ez egy extra feladat, a változtatást nem emiatt kérem be, hanem kizárólag az első 2-be írt kommentjeim miatt. Rádbízom hogy az extrát is javítod e vagy sem. Összességében nagyon szép munka, örülök hogy már most function-öket használsz!

2024-10-14 11:54 UTC, NagyIstvanGabor commented on homeworks/nagynorbert/3_conditionals_loops/rock_paper_scissors.py
> +while True:
ez a while blokk is lehetne egy function, pl `get_rounds()`, ami visszaadja hogy hány kört fognak játszani.

2024-10-14 11:54 UTC, NagyIstvanGabor commented on homeworks/nagynorbert/3_conditionals_loops/rock_paper_scissors.py
> +def evaluate_signs(sum_points_1,sum_points_2,player_1_sign,player_2_sign):
elég hosszú így minden lehetséges kimenetelt megvizsgálni, ebben a formában talán egyszerűbb ha van egy ún. mapping-et a győztes kombinációkról, és ezeket vizsgálod:

```
def evaluate_signs(sum_points_1, sum_points_2, player_1_sign, player_2_sign):

    winning_combinations = {
        "rock": "scissors",
        "scissors": "paper",
        "paper": "rock"
    }
    
    if player_1_sign == player_2_sign:
        return sum_points_1, sum_points_2
    elif winning_combinations[player_1_sign] == player_2_sign:
        return sum_points_1 + 1, sum_points_2
    else:
        return sum_points_1, sum_points_2 + 1
```

Illetve szuper lenne ha kapnánk minden körben is visszajelzést arról, hogy az adott kört ki nyerte, és jelenleg mi az állás.

2024-10-14 11:54 UTC, NagyIstvanGabor commented on homeworks/nagynorbert/3_conditionals_loops/rock_paper_scissors.py
> +input_list_1 = []
Ezt, hogy 2 ilyen listát csinálsz, lehetne úgy egyszerűsíteni, hogy van egy dictionary-d két key-jel:
"player_1_inputs" és "player_2_inputs". mindkettőhöz egy lista tartozik, és ezekbe a listákba append-elsz.
Ez nem hiba, csak egy egyszerűsítési lehetőség.

2024-10-14 11:54 UTC, NagyIstvanGabor commented on homeworks/nagynorbert/3_conditionals_loops/ticket_booking.py
> +while True:
Ez is lehetne egy function, amit az elején meghívsz és visszaadja a választott film címét.

2024-10-14 18:34 UTC, nagynorbi commented
Javítottam, köszi! 
Google Classroom-ban elfelejtettem átnyomni a házit készre, most átnyomtam viszont a státusz késdelmes leadás lett. Remélem ez nem jelent gondot.

2024-10-15 20:49 UTC, NagyIstvanGabor approved these changes
Szia!

Köszi szépen, approve-oltam!
Mehet a merge. Semmi gond, ha classroom-on nem nyomtad be időben, sokan teljesen elfelejtik. Nem szoktam ezzel foglalkozni, a pontot ugyanúgy megkapjátok ha itt githubon minden oké.

2024-10-17 07:16 UTC, merged